# Generated by Django 3.2.9 on 2022-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_pin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_pin',
            name='pin',
            field=models.CharField(help_text='this is the generated pin for the user to enable the user to recieve token request offers which is a one time pin.', max_length=4, null=True, verbose_name='Pin'),
        ),
    ]
