# Generated by Django 3.2.9 on 2022-07-28 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_pin', '0002_alter_generate_pin_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_pin',
            name='user',
            field=models.ForeignKey(help_text='The user that is currently sending kroon token.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generator Profile'),
        ),
    ]
