# Generated by Django 3.2.9 on 2022-02-16 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KroonGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('email', models.EmailField(help_text='this email field hold the users email address which will be verified during registration so note user can only gift kroon token to unregistered users.', max_length=254, null=True, verbose_name='Email')),
                ('amount', models.FloatField(help_text='the amount in kroon token to be sent the user.', null=True, verbose_name='Amount In Kroon')),
                ('redeem_pin', models.CharField(help_text='the redeem pin is set to be used when verifying a gift token which on successful operation the amount will be sent to the user.', max_length=255, null=True, verbose_name='Redeem Pin')),
                ('settled', models.BooleanField(default=False, help_text='this indicates whether the gift token is used by the user or not', null=True, verbose_name='Kroon Gift Settled')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kroon_gift_sender', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Gift Kroon',
                'verbose_name_plural': 'Gift Kroon',
                'ordering': ('-created_date',),
            },
        ),
    ]
