# Generated by Django 3.2.9 on 2022-02-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('kroon_gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kroongift',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country residence of the customer. kroon gift can only be accepted by a user from the same country with the sender', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Gift Country'),
        ),
    ]
