# Generated by Django 3.2.9 on 2022-02-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_gift', '0002_kroongift_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='kroongift',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=355, null=True, verbose_name='Transactional ID'),
        ),
    ]
