# Generated by Django 3.2.9 on 2022-07-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_language'),
        ('kroon_gift', '0006_alter_kroongift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroongift',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country residence of the customer. kroon gift can only be accepted by a user from the same country with the sender', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='Gift Country'),
        ),
    ]
