# Generated by Django 3.2.9 on 2021-12-13 23:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('currency', models.CharField(help_text='currency of which the country rate should be calculated.', max_length=5, null=True, verbose_name='currency')),
                ('token_rate', models.PositiveIntegerField(help_text='The token rate for each currency', null=True, verbose_name='Token Rate')),
            ],
            options={
                'verbose_name': 'Token Rate',
                'verbose_name_plural': 'Token Rate',
                'ordering': ('created_date',),
            },
        ),
    ]
