# Generated by Django 3.2.9 on 2021-12-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenrate',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('SAR', 'SAR'), ('GHZ', 'GHZ')], help_text='currency of which the country rate should be calculated.', max_length=5, null=True, verbose_name='currency'),
        ),
    ]
