# Generated by Django 3.2.9 on 2021-12-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0004_auto_20211220_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetokenfees',
            name='agent_fee',
            field=models.CharField(blank=True, help_text='the agent fee should take place when ever an agent is meant to handle kroon token request. which will be added along side with vat fees  and application fees.', max_length=3, null=True, verbose_name='Agent Fees'),
        ),
        migrations.AlterField(
            model_name='purchasetokenfees',
            name='application_fee',
            field=models.CharField(help_text='identify the application fees for the current rate.', max_length=3, null=True, verbose_name='Application Fees'),
        ),
        migrations.AlterField(
            model_name='purchasetokenfees',
            name='vat_fee',
            field=models.CharField(help_text='the vat fee for any transaction which will be calculated with the kroon token amount and application fees.', max_length=3, null=True, verbose_name='Vat Fees'),
        ),
        migrations.AlterField(
            model_name='withdrawtokenfees',
            name='agent_fee',
            field=models.CharField(blank=True, help_text='the agent fee should take place when ever an agent is meant to handle kroon token request. which will be added along side with vat fees  and application fees.', max_length=4, null=True, verbose_name='Agent Fees'),
        ),
        migrations.AlterField(
            model_name='withdrawtokenfees',
            name='application_fee',
            field=models.CharField(help_text='identify the application fees for the current rate.', max_length=4, null=True, verbose_name='Application Fees'),
        ),
        migrations.AlterField(
            model_name='withdrawtokenfees',
            name='vat_fee',
            field=models.CharField(help_text='the vat fee for any transaction which will be calculated with the kroon token amount and application fees.', max_length=4, null=True, verbose_name='Vat Fees'),
        ),
    ]
