# Generated by Django 3.2.9 on 2021-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0005_auto_20211220_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetokenfees',
            name='active',
            field=models.BooleanField(default=False, help_text='active status determines whether fees and vat fees are active or not.', null=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='withdrawtokenfees',
            name='active',
            field=models.BooleanField(default=False, help_text='active status determines whether fees and vat fees are active or not.', null=True, verbose_name='Active'),
        ),
    ]
