# Generated by Django 3.2.9 on 2022-01-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('kroon_token', '0006_auto_20211220_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetokenfees',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country of Residence'),
        ),
        migrations.AddField(
            model_name='withdrawtokenfees',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country of Residence'),
        ),
    ]
