# Generated by Django 3.2.9 on 2022-02-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('kroon_token', '0007_auto_20220119_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetokenfees',
            name='operator',
            field=models.CharField(choices=[('cards payments', 'Card Payment'), ('agent', 'Agent')], help_text='this section hold the operator which the current fees should be applied to.', max_length=300, null=True, verbose_name='Operators'),
        ),
        migrations.AlterField(
            model_name='tokenrate',
            name='currency',
            field=models.ForeignKey(help_text='currency of which the country rate should be calculated.', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='withdrawtokenfees',
            name='operator',
            field=models.CharField(choices=[('bank accounts', 'Bank Accounts'), ('agent cashout', 'Agent Cashout')], help_text='this section hold the withdrawal operator which the current fees should be applied to.', max_length=300, null=True, verbose_name='Withdraw Operators'),
        ),
    ]
