# Generated by Django 3.2.9 on 2022-03-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0011_alter_withdrawtokenfees_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetokenfees',
            name='top_up_limit',
            field=models.PositiveIntegerField(blank=True, help_text='this holds the topup limitation for the each country.', null=True, verbose_name='Top Up Limit'),
        ),
        migrations.AddField(
            model_name='withdrawtokenfees',
            name='withdrawal_limit',
            field=models.PositiveIntegerField(blank=True, help_text='this holds the Withdrawal limitation for the each country.', null=True, verbose_name='Withdrawal Limit'),
        ),
    ]
