# Generated by Django 3.2.9 on 2022-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0012_auto_20220302_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetokenfees',
            name='top_up_limit',
            field=models.CharField(blank=True, help_text='this holds the topup limitation for the each country.', max_length=10, null=True, verbose_name='Top Up Limit'),
        ),
        migrations.AlterField(
            model_name='withdrawtokenfees',
            name='withdrawal_limit',
            field=models.CharField(blank=True, help_text='this holds the Withdrawal limitation for the each country.', max_length=10, null=True, verbose_name='Withdrawal Limit'),
        ),
    ]
