# Generated by Django 3.2.9 on 2022-03-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0014_auto_20220320_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawtokenfees',
            name='withdrawal_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='this holds the Withdrawal limitation for the each country.', max_digits=300, null=True, verbose_name='Withdrawal Limit'),
        ),
    ]
