# Generated by Django 3.2.9 on 2022-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0016_auto_20220728_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetokenfees',
            name='kroon_trasfer_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='this is the transfer rate for any transaction which will be calculated with the kroon token amount ', max_digits=300, max_length=3, null=True, verbose_name='Kroon Transfer Rate'),
        ),
        migrations.AddField(
            model_name='purchasetokenfees',
            name='virtual_card_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='this is the virtual card fees for creating a virtual card for the merchant user, this fees is meant to the be set in the a trading currency i:e USD or AUD and many more  ', max_digits=300, max_length=3, null=True, verbose_name='Virtual Card Fees'),
        ),
    ]
