# Generated by Django 3.2.9 on 2022-11-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0017_auto_20221109_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawtokenfees',
            name='withdrawal_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the withdrawal fee for any transaction which will be calculated with the initial amount fee before the withdrawal process.', max_digits=300, max_length=4, null=True, verbose_name='Withdrawal Fee'),
        ),
    ]
