# Generated by Django 3.2.9 on 2023-02-15 09:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_token', '0019_rename_kroon_trasfer_rate_purchasetokenfees_kroon_transfer_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_Convertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('default_currency', models.CharField(blank=True, help_text='this is set to be the default currency which will be converted using the conversion currency', max_length=4, null=True, verbose_name='Default Currency')),
                ('converted_currency', models.CharField(blank=True, default='USD', help_text='the converted currency will be set to the default currency which will be converted to', max_length=4, null=True, verbose_name='Converted Currency')),
                ('convertion_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='this holds the convertion rate for each country.', max_digits=300, null=True, verbose_name='Convertion Rate')),
            ],
            options={
                'verbose_name': 'Currencies Convertion',
                'verbose_name_plural': 'Currencies Convertion',
                'ordering': ('-created_date',),
            },
        ),
    ]
