# Generated by Django 3.2.9 on 2022-04-18 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Topup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('payment_ref', models.CharField(help_text='The payment identification number sent from the payment gateway.', max_length=50, null=True, verbose_name='Payment Ref No')),
                ('payment_method', models.CharField(default='ONLINE PAYMENT', help_text='The payment method used while paying for an order.', max_length=150, null=True, verbose_name='Payment Method')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for the above order by the customer.', max_digits=300, null=True, verbose_name='Amount Paid')),
                ('amount_in_kroon', models.DecimalField(decimal_places=2, help_text='Amount paid for the above order by the customer.', max_digits=300, null=True, verbose_name='Kroon Amount Paid')),
                ('currency', models.CharField(help_text='payment currency is the currency code for the user while making payment', max_length=4, null=True, verbose_name='Payment Currency')),
                ('verified', models.BooleanField(blank=True, default=False, help_text='Verified payment status to identify if the payment is been verified by the payment gateway or not.', null=True, verbose_name='Payment Verification')),
                ('action', models.CharField(default='KROON WALLET TOPUP', help_text='The payment action for the current transaction.', max_length=150, null=True, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('successful', 'Successful'), ('failed', 'failed')], default='pending', help_text='payment status to identify if the payment is been verified by the payment gateway or not.', max_length=255, null=True, verbose_name='Payment Status')),
                ('pending_duration', models.DateTimeField(default=django.utils.timezone.now, help_text='duration of which the pending topup will be expired if no action is not been take.', null=True, verbose_name='Pending Topup Duration')),
                ('settled', models.BooleanField(default=False, help_text='this indicates whether the payment is been settled or not.', null=True, verbose_name='Payment Settled')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup_users', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'All TopUp Payment',
                'verbose_name_plural': 'All TopUp Payment',
                'ordering': ('-created_date',),
            },
        ),
    ]
