# Generated by Django 4.2.3 on 2023-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_topup_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment_topup",
            name="etransac_ref",
            field=models.CharField(
                blank=True,
                help_text="this shows the payment ref that is will returned by the payment gateway.",
                max_length=100,
                null=True,
                verbose_name="Etransac Payment Ref ",
            ),
        ),
    ]
