# Generated by Django 3.2.9 on 2022-03-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_queue', '0002_alter_testmodels_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodels',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
