# Generated by Django 3.2.9 on 2022-06-01 22:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk_E_Learning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('title', models.CharField(blank=True, help_text='This hold the e-learning title of this particular Kiosk E-Learning.', max_length=255, null=True, verbose_name='Kiosk E-Learning')),
                ('vd_link', models.URLField(blank=True, help_text='This section represents the video link for the E-Learning video', null=True, verbose_name='E Learning Video Link')),
            ],
            options={
                'verbose_name': 'Kiosk E-Learning',
                'verbose_name_plural': 'Kiosk E-Learning',
                'ordering': ('-created_date',),
            },
        ),
    ]
