# Generated by Django 3.2.9 on 2022-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_language'),
        ('e_learning', '0002_kiosk_e_learning_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk_e_learning',
            name='e_leanring_country',
            field=models.ManyToManyField(help_text=' this is the country that will be able to see this ad image', to='locations.Country'),
        ),
        migrations.AddField(
            model_name='kiosk_e_learning',
            name='vd_thumbnail',
            field=models.ImageField(blank=True, help_text='this holds the e-leanry video thumbnail for the particular learning vd', null=True, upload_to='', verbose_name='E-Learning video thumbnail'),
        ),
    ]
