# Generated by Django 4.2.3 on 2023-08-10 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("e_learning", "0003_auto_20220613_1241"),
    ]

    operations = [
        migrations.CreateModel(
            name="App_Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user for whom account belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_survey",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Survey",
                "verbose_name_plural": "Merchant Surveys",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="AppSurveyQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "survey_question",
                    models.CharField(
                        blank=True,
                        help_text="this shows rthe question of the survey",
                        max_length=300,
                        null=True,
                        verbose_name="Survey Questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Survey Question",
                "verbose_name_plural": "App Surveys Question",
            },
        ),
        migrations.CreateModel(
            name="SurveyQA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "survey_answer",
                    models.CharField(
                        blank=True,
                        help_text="the hold the answer of the survey",
                        max_length=300,
                        null=True,
                        verbose_name="Survey Answer",
                    ),
                ),
                (
                    "survey_qa",
                    models.ForeignKey(
                        help_text="this hold the survey question and answers",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_field",
                        to="e_learning.app_survey",
                        verbose_name="Survey QA",
                    ),
                ),
                (
                    "survey_questions_id",
                    models.ForeignKey(
                        help_text="this hold the survey question ",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_field",
                        to="e_learning.appsurveyquestion",
                        verbose_name="Survey QA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Q and A ",
                "verbose_name_plural": "Survey Q and A",
                "ordering": ("-created_date",),
            },
        ),
    ]
