# Generated by Django 4.2.5 on 2023-10-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0005_alter_app_survey_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyqa",
            name="survey_qa",
            field=models.ForeignKey(
                help_text="this hold the user account that answered the survey questions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_user",
                to="e_learning.app_survey",
                verbose_name="User Account",
            ),
        ),
    ]
