# Generated by Django 3.2.9 on 2022-01-27 11:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeWebhookMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('received_at', models.DateTimeField(help_text='When we received the event.')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Message',
                'verbose_name_plural': 'Webhook Message',
                'ordering': ('-created_date',),
            },
        ),
        migrations.AddIndex(
            model_name='acmewebhookmessage',
            index=models.Index(fields=['received_at'], name='webhooks_ac_receive_b791f2_idx'),
        ),
    ]
