# Generated by Django 4.1.9 on 2023-06-23 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0006_auto_20221212_1021"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business_Agreements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True,
                        help_text="this hold the document file name",
                        max_length=200,
                        null=True,
                        verbose_name="Document Name",
                    ),
                ),
                (
                    "document_thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="this hold the document file which is downloadable by the merchants ",
                        null=True,
                        upload_to="business_document",
                        verbose_name="Document Thumbnail",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        help_text="this hold the document file which can be in any format",
                        null=True,
                        upload_to="business_document_file",
                        verbose_name="Document File",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="this indicates whether the document is available or not",
                        null=True,
                        verbose_name="Document Available",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Document",
                "verbose_name_plural": "Business Document",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="Shares_Agreements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="this represents the name of the company that is issuring the shares.",
                        max_length=200,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "company_share",
                    models.PositiveIntegerField(
                        help_text="the number of shares the company is issuring",
                        null=True,
                        verbose_name="Company Share",
                    ),
                ),
                (
                    "business_logo",
                    models.ImageField(
                        help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                        null=True,
                        upload_to="business_document",
                        verbose_name="Business Logo",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        help_text="this represents the name of the owner.",
                        max_length=200,
                        null=True,
                        verbose_name="Owner Name",
                    ),
                ),
                (
                    "non_compete_period",
                    models.CharField(
                        help_text="the non completed period of the share agreements",
                        max_length=200,
                        null=True,
                        verbose_name="Non Compete Period",
                    ),
                ),
                (
                    "company_country",
                    models.ForeignKey(
                        help_text="This refers to the country in which the business or company operates or conducts its primary activities. It signifies the geographic location where the business or company carries out its production, sales, and service delivery",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_country",
                        to="locations.country",
                        verbose_name="Company Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shares Agreements",
                "verbose_name_plural": "Shares Agreements",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="Shares_Signatures",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="this represents the name of the person.",
                        max_length=200,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="this represents the name of the person.",
                        max_length=200,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "share",
                    models.PositiveIntegerField(
                        help_text="The number of hours the employee is expected to work per week.",
                        null=True,
                        verbose_name="Share",
                    ),
                ),
                (
                    "share_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The salary of the employee.",
                        max_digits=10,
                        null=True,
                        verbose_name="Share Price",
                    ),
                ),
                (
                    "shares_signature",
                    models.ImageField(
                        help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                        null=True,
                        upload_to="shares_signatures",
                        verbose_name="Shares Signature",
                    ),
                ),
                (
                    "agreements",
                    models.ForeignKey(
                        blank=True,
                        help_text="The agreements assocaited to the documents.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements_docs",
                        to="kiosk_agreements.shares_agreements",
                        verbose_name="Shares Agreements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shares Signature",
                "verbose_name_plural": "Shares Signature",
                "ordering": ("-created_date",),
            },
        ),
        migrations.AddField(
            model_name="shares_agreements",
            name="share_holders",
            field=models.ManyToManyField(
                help_text="this represents the share holders details which includes the signatures ",
                to="kiosk_agreements.shares_signatures",
                verbose_name="Share holder",
            ),
        ),
        migrations.AddField(
            model_name="shares_agreements",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user associated with this business agreement.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreement_owner_SA",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Accounts",
            ),
        ),
        migrations.CreateModel(
            name="Loan_Agreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(
                        help_text="this is the full name of the borrower",
                        max_length=200,
                        null=True,
                        verbose_name="Borrower Name",
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(
                        help_text="this is the full name of the lender",
                        max_length=200,
                        null=True,
                        verbose_name="Lender Name",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount that will be issued.",
                        max_digits=10,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "date_of_execution",
                    models.DateField(
                        help_text="The date of the execution.", null=True, verbose_name="Date Of Execution"
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        help_text="this holds the payment frequency.",
                        max_length=200,
                        null=True,
                        verbose_name="Payment Frequency",
                    ),
                ),
                (
                    "first_payment_date",
                    models.DateField(
                        help_text="the first initial payment date is recorded.",
                        null=True,
                        verbose_name="First Payment Date",
                    ),
                ),
                (
                    "amount_of_each_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The price of good and service.",
                        max_digits=10,
                        null=True,
                        verbose_name="Amount Of Each Payment",
                    ),
                ),
                (
                    "interest_name",
                    models.PositiveIntegerField(
                        help_text="this have the percentage of the interest to be paid",
                        null=True,
                        verbose_name="Interest Name",
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        help_text="the record hold the asset, that is submitted for the loan",
                        max_length=200,
                        null=True,
                        verbose_name="Asset",
                    ),
                ),
                (
                    "lender_address",
                    models.CharField(
                        help_text="the lender home or work address",
                        max_length=200,
                        null=True,
                        verbose_name="Lender Address",
                    ),
                ),
                (
                    "borrower_address",
                    models.CharField(
                        help_text="the borrower home or work address",
                        max_length=200,
                        null=True,
                        verbose_name="Borrower Address",
                    ),
                ),
                (
                    "loaner_type",
                    models.CharField(
                        help_text="this holds the seller type", max_length=200, null=True, verbose_name="Loaner Type"
                    ),
                ),
                (
                    "asset_location",
                    models.CharField(
                        help_text="the asset address", max_length=200, null=True, verbose_name="Asset Location"
                    ),
                ),
                (
                    "borrower_type",
                    models.CharField(
                        help_text="this holds the borrower type",
                        max_length=200,
                        null=True,
                        verbose_name="Borrower Type",
                    ),
                ),
                (
                    "business_logo",
                    models.ImageField(
                        help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                        null=True,
                        upload_to="business_document",
                        verbose_name="Business Logo",
                    ),
                ),
                (
                    "formatted_date",
                    models.DateField(
                        help_text="The date is formatted to when the agreement is taken.",
                        null=True,
                        verbose_name="Formatted Date",
                    ),
                ),
                (
                    "lender_country",
                    models.ForeignKey(
                        help_text="This refers to the lenders country in which the business or company operates or conducts its primary activities. It signifies the geographic location where the business or company carries out its production, sales, and service delivery",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lender_country",
                        to="locations.country",
                        verbose_name="Lender Country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user associated with this business agreement.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_owner_LA",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Agreements",
                "verbose_name_plural": "Loan Agreements",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="Goods_And_Services_Agreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        help_text="this represents the seller name .",
                        max_length=200,
                        null=True,
                        verbose_name="Seller Name",
                    ),
                ),
                (
                    "seller_address",
                    models.CharField(
                        help_text="the seller home or work address.",
                        max_length=200,
                        null=True,
                        verbose_name="Seller Address ",
                    ),
                ),
                (
                    "business_logo",
                    models.ImageField(
                        help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                        null=True,
                        upload_to="business_document",
                        verbose_name="Business Logo",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        help_text="this represents the owners name .",
                        max_length=200,
                        null=True,
                        verbose_name="Owner Name",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        help_text="this represents the name of the buyer that is issuring the shares.",
                        max_length=200,
                        null=True,
                        verbose_name="Buyer Name",
                    ),
                ),
                (
                    "buyer_address",
                    models.CharField(
                        help_text="this represents the buyer address.",
                        max_length=200,
                        null=True,
                        verbose_name="Buyer Address",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="the type of the share agreement", max_length=200, null=True, verbose_name="Type"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="this represents the name of the product ",
                        max_length=200,
                        null=True,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "product_quantity",
                    models.CharField(
                        help_text="this represents the quantity of the product ",
                        max_length=200,
                        null=True,
                        verbose_name="Product Quantity",
                    ),
                ),
                (
                    "price_of_good_and_service",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The price of good and service.",
                        max_digits=10,
                        null=True,
                        verbose_name="Price of Goods And Services",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        help_text="the delivery service address.",
                        max_length=200,
                        null=True,
                        verbose_name="Delivery Address",
                    ),
                ),
                (
                    "buyer_type",
                    models.CharField(
                        help_text="this holds the buyer type", max_length=200, null=True, verbose_name="Buyer Type"
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        help_text="this holds the seller type", max_length=200, null=True, verbose_name="Seller Type"
                    ),
                ),
                (
                    "formatted_date",
                    models.DateField(
                        help_text="The date is formatted to when the agreement is taken.",
                        null=True,
                        verbose_name="Formatted Date",
                    ),
                ),
                (
                    "buyer_country",
                    models.ForeignKey(
                        help_text="This refers to the country in which the business or company operates or conducts its primary activities. It signifies the geographic location where the business or company carries out its production, sales, and service delivery",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_country",
                        to="locations.country",
                        verbose_name="Buyer Country",
                    ),
                ),
                (
                    "seller_country",
                    models.ForeignKey(
                        help_text="This refers to the sellers country in which the business or company operates or conducts its primary activities. It signifies the geographic location where the business or company carries out its production, sales, and service delivery",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_country",
                        to="locations.country",
                        verbose_name="Seller Country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user associated with this business agreement.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_owner_GnS",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods and Services Agreements",
                "verbose_name_plural": "Goods and Services Agreements",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="Agreements_Info",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="A business name refers to the official name by which the company, organization, or sole proprietor operates and conducts its business activities. It is the name under which a business is registered and recognized legally.",
                        max_length=200,
                        null=True,
                        verbose_name="Business Name",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        help_text="The industry in which the business operates.",
                        max_length=200,
                        null=True,
                        verbose_name="Industry",
                    ),
                ),
                (
                    "business_logo",
                    models.ImageField(
                        help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                        null=True,
                        upload_to="business_document",
                        verbose_name="Business Logo",
                    ),
                ),
                (
                    "business_owner_name",
                    models.CharField(
                        help_text="A business name refers to the official name by which a company, organization, or sole proprietor operates and conducts its business activities. It is the name under which a business is registered and recognized legally.",
                        max_length=200,
                        null=True,
                        verbose_name="Business Owner Name",
                    ),
                ),
                (
                    "business_address",
                    models.CharField(
                        help_text="The business address refers to the physical location where a business is located or operates from. It serves as the specific street address, city, state, and postal code that uniquely identifies the business's place of operation.",
                        max_length=200,
                        null=True,
                        verbose_name="Business Address",
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        help_text="An employee name refers to the personal name given to an individual who is employed by a company or organization",
                        max_length=200,
                        null=True,
                        verbose_name="Employee Name",
                    ),
                ),
                (
                    "employee_address",
                    models.CharField(
                        help_text="The term employee address refers to the residential address or location where an employee resides. It is the physical address where an employee lives and is used for communication and administrative purposes by the employer.",
                        max_length=200,
                        null=True,
                        verbose_name="Employee Address",
                    ),
                ),
                (
                    "employee_position",
                    models.CharField(
                        help_text="An employee position refers to the specific role or job title held by an individual within an organization. It signifies the responsibilities, duties, and level of authority associated with that particular role. ",
                        max_length=200,
                        null=True,
                        verbose_name="Employee Position",
                    ),
                ),
                (
                    "employee_start_date",
                    models.DateField(
                        help_text="The date when the employee started working.",
                        null=True,
                        verbose_name="Employee Start Date",
                    ),
                ),
                (
                    "employment_term",
                    models.CharField(
                        help_text="The term or duration of the employment agreement.",
                        max_length=100,
                        null=True,
                        verbose_name="Employment Term",
                    ),
                ),
                (
                    "employee_end_date",
                    models.DateField(
                        help_text="The date when the employee's employment ends, if applicable.",
                        null=True,
                        verbose_name="Employee End Date",
                    ),
                ),
                (
                    "employee_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The salary of the employee.",
                        max_digits=10,
                        null=True,
                        verbose_name="Employee Salary",
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        help_text="The frequency at which the employee is paid.",
                        max_length=100,
                        null=True,
                        verbose_name="Payment Frequency",
                    ),
                ),
                (
                    "employee_responsibilities",
                    models.TextField(
                        help_text="The responsibilities and duties of the employee.",
                        verbose_name="Employee Responsibilities",
                    ),
                ),
                (
                    "weekly_hours",
                    models.PositiveIntegerField(
                        help_text="The number of hours the employee is expected to work per week.",
                        null=True,
                        verbose_name="Weekly Hours",
                    ),
                ),
                (
                    "travel_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether travel is required for the employee.",
                        null=True,
                        verbose_name="Travel Required",
                    ),
                ),
                (
                    "company_policies",
                    models.TextField(
                        help_text="The policies and guidelines of the company.", verbose_name="Company Policies"
                    ),
                ),
                (
                    "business_country",
                    models.ForeignKey(
                        help_text="This refers to the country in which the business operates or conducts its primary activities. It signifies the geographic location where the business carries out its production, sales, and service delivery",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_country",
                        to="locations.country",
                        verbose_name="Business Country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user associated with this business agreement.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement info",
                "verbose_name_plural": "Agreement info",
                "ordering": ("-created_date",),
            },
        ),
    ]
