# Generated by Django 4.1.9 on 2023-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk_agreements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods_and_services_agreement",
            name="signature",
            field=models.ImageField(
                blank=True,
                help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                null=True,
                upload_to="signatures",
                verbose_name=" Signature",
            ),
        ),
        migrations.AddField(
            model_name="loan_agreement",
            name="signature",
            field=models.ImageField(
                blank=True,
                help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                null=True,
                upload_to="signatures",
                verbose_name=" Signature",
            ),
        ),
        migrations.AlterField(
            model_name="shares_signatures",
            name="shares_signature",
            field=models.ImageField(
                blank=True,
                help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                null=True,
                upload_to="shares_signatures",
                verbose_name="Shares Signature",
            ),
        ),
    ]
