# Generated by Django 4.1.9 on 2023-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk_agreements", "0002_goods_and_services_agreement_signature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods_and_services_agreement",
            name="price_of_good_and_service",
            field=models.CharField(
                blank=True,
                help_text="The price of good and service.",
                max_length=200,
                null=True,
                verbose_name="Price of Goods And Services",
            ),
        ),
        migrations.AlterField(
            model_name="loan_agreement",
            name="amount",
            field=models.CharField(
                blank=True,
                help_text="The amount that will be issued.",
                max_length=200,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="loan_agreement",
            name="amount_of_each_payment",
            field=models.CharField(
                blank=True,
                help_text="The price of good and service.",
                max_length=200,
                null=True,
                verbose_name="Amount Of Each Payment",
            ),
        ),
        migrations.AlterField(
            model_name="shares_signatures",
            name="share_price",
            field=models.CharField(
                blank=True,
                help_text="The salary of the employee.",
                max_length=200,
                null=True,
                verbose_name="Share Price",
            ),
        ),
    ]
