# Generated by Django 4.1.9 on 2023-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk_agreements", "0004_shares_agreements_formatted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreements_info",
            name="employee_signature",
            field=models.ImageField(
                blank=True,
                help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                null=True,
                upload_to="signatures",
                verbose_name="Employee Signature",
            ),
        ),
        migrations.AddField(
            model_name="agreements_info",
            name="formatted_date",
            field=models.CharField(
                blank=True,
                help_text="The date is formatted to when the agreement is taken.",
                max_length=200,
                null=True,
                verbose_name="Formatted Date",
            ),
        ),
        migrations.AddField(
            model_name="agreements_info",
            name="signature",
            field=models.ImageField(
                blank=True,
                help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                null=True,
                upload_to="signatures",
                verbose_name=" Signature",
            ),
        ),
        migrations.AlterField(
            model_name="agreements_info",
            name="employee_end_date",
            field=models.CharField(
                blank=True,
                help_text="The date when the employee's employment ends, if applicable.",
                max_length=100,
                null=True,
                verbose_name="Employee End Date",
            ),
        ),
        migrations.AlterField(
            model_name="agreements_info",
            name="employee_salary",
            field=models.CharField(
                blank=True,
                help_text="The salary of the employee.",
                max_length=100,
                null=True,
                verbose_name="Employee Salary",
            ),
        ),
        migrations.AlterField(
            model_name="agreements_info",
            name="employee_start_date",
            field=models.CharField(
                blank=True,
                help_text="The date when the employee started working.",
                max_length=100,
                null=True,
                verbose_name="Employee Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="agreements_info",
            name="weekly_hours",
            field=models.CharField(
                blank=True,
                help_text="The number of hours the employee is expected to work per week.",
                max_length=200,
                null=True,
                verbose_name="Weekly Hours",
            ),
        ),
        migrations.AlterField(
            model_name="goods_and_services_agreement",
            name="formatted_date",
            field=models.CharField(
                blank=True,
                help_text="The date is formatted to when the agreement is taken.",
                max_length=200,
                null=True,
                verbose_name="Formatted Date",
            ),
        ),
        migrations.AlterField(
            model_name="loan_agreement",
            name="date_of_execution",
            field=models.CharField(
                blank=True,
                help_text="The date of the execution.",
                max_length=200,
                null=True,
                verbose_name="Date Of Execution",
            ),
        ),
        migrations.AlterField(
            model_name="loan_agreement",
            name="first_payment_date",
            field=models.CharField(
                blank=True,
                help_text="the first initial payment date is recorded.",
                max_length=100,
                null=True,
                verbose_name="First Payment Date",
            ),
        ),
        migrations.AlterField(
            model_name="loan_agreement",
            name="formatted_date",
            field=models.CharField(
                blank=True,
                help_text="The date is formatted to when the agreement is taken.",
                max_length=200,
                null=True,
                verbose_name="Formatted Date",
            ),
        ),
        migrations.AlterField(
            model_name="loan_agreement",
            name="interest_name",
            field=models.CharField(
                blank=True,
                help_text="this have the percentage of the interest to be paid",
                max_length=200,
                null=True,
                verbose_name="Interest Name",
            ),
        ),
        migrations.AlterField(
            model_name="shares_agreements",
            name="company_share",
            field=models.CharField(
                help_text="the number of shares the company is issuring",
                max_length=200,
                null=True,
                verbose_name="Company Share",
            ),
        ),
        migrations.AlterField(
            model_name="shares_agreements",
            name="formatted_date",
            field=models.CharField(
                blank=True,
                help_text="The date is formatted to when the agreement is taken.",
                max_length=100,
                null=True,
                verbose_name="Formatted Date",
            ),
        ),
        migrations.AlterField(
            model_name="shares_agreements",
            name="owner_name",
            field=models.CharField(
                blank=True,
                help_text="this represents the name of the owner.",
                max_length=200,
                null=True,
                verbose_name="Owner Name",
            ),
        ),
        migrations.AlterField(
            model_name="shares_signatures",
            name="share",
            field=models.CharField(
                help_text="The number of hours the employee is expected to work per week.",
                max_length=200,
                null=True,
                verbose_name="Share",
            ),
        ),
    ]
