# Generated by Django 4.1.9 on 2023-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk_agreements", "0006_alter_agreements_info_business_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shares_agreements",
            name="signature",
            field=models.ImageField(
                blank=True,
                help_text="A business logo is a graphic or symbol that represents a company or brand. It is a visual representation of the business and plays a crucial role in establishing brand identity and recognition",
                null=True,
                upload_to="signatures",
                verbose_name="Signature",
            ),
        ),
    ]
