# Generated by Django 3.2.9 on 2022-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_kyc', '0003_marchantkycapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='photo_id',
            field=models.ImageField(help_text="The front side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", storage='uploads/kyc/', upload_to='', verbose_name='Photo ID(front)'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='photo_id_back',
            field=models.ImageField(blank=True, help_text="The back side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", null=True, storage='uploads/kyc/', upload_to='', verbose_name='Photo ID(back)'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='selfie_with_id',
            field=models.ImageField(blank=True, help_text='Upload a photo with yourself and your Passport or both sides of the ID Card. The face and the document must be clearly visible.', null=True, storage='uploads/kyc/', upload_to='', verbose_name='Selfie with ID'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='photo_id',
            field=models.ImageField(help_text="The front side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", storage='uploads/kyc/', upload_to='', verbose_name='Photo ID(front)'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='photo_id_back',
            field=models.ImageField(blank=True, help_text="The back side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", null=True, storage='uploads/kyc/', upload_to='', verbose_name='Photo ID(back)'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='selfie_with_id',
            field=models.ImageField(blank=True, help_text='Upload a photo with yourself and your Passport or both sides of the ID Card. The face and the document must be clearly visible.', null=True, storage='uploads/kyc/', upload_to='', verbose_name='Selfie with ID'),
        ),
    ]
