# Generated by Django 3.2.9 on 2022-01-25 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kroon_kyc', '0004_auto_20220124_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='photo_id',
            field=models.ImageField(help_text="The front side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", upload_to='uploads/kyc/', verbose_name='Photo ID(front)'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='photo_id_back',
            field=models.ImageField(blank=True, help_text="The back side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", null=True, upload_to='uploads/kyc/', verbose_name='Photo ID(back)'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='selfie_with_id',
            field=models.ImageField(blank=True, help_text='Upload a photo with yourself and your Passport or both sides of the ID Card. The face and the document must be clearly visible.', null=True, upload_to='uploads/kyc/', verbose_name='Selfie with ID'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Unique identifier of the user that owns the activity.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='KYC User'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='photo_id',
            field=models.ImageField(help_text="The front side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", upload_to='uploads/kyc/', verbose_name='Photo ID(front)'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='photo_id_back',
            field=models.ImageField(blank=True, help_text="The back side of The user's Photo Identitification. Chosen credential must not be expired. Document should be good condition and clearly visible. File is at least 1 MB in size and has at least 300 dpi resolution.", null=True, upload_to='uploads/kyc/', verbose_name='Photo ID(back)'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='selfie_with_id',
            field=models.ImageField(blank=True, help_text='Upload a photo with yourself and your Passport or both sides of the ID Card. The face and the document must be clearly visible.', null=True, upload_to='uploads/kyc/', verbose_name='Selfie with ID'),
        ),
    ]
