# Generated by Django 3.2.9 on 2022-02-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_kyc', '0005_auto_20220125_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycapplication',
            name='status_update_date',
        ),
    ]
