# Generated by Django 3.2.9 on 2022-02-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_kyc', '0006_remove_kycapplication_status_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchantkycapplication',
            name='kyc_submitted_ip_address',
        ),
    ]
