# Generated by Django 3.2.9 on 2022-02-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_kyc', '0007_remove_marchantkycapplication_kyc_submitted_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycapplication',
            name='kyc_submitted_ip_address',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='registered_ip_address',
        ),
    ]
