# Generated by Django 3.2.9 on 2022-02-26 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kroon_kyc', '0010_auto_20220226_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='birth_date',
            field=models.DateField(help_text="The user's date of birth as per the identification document. The date of birth must match The user's ID", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='business_email',
            field=models.EmailField(help_text='The primary e-mail address of the user business submitting KYC application', max_length=150, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='business_registration_number',
            field=models.CharField(help_text='the business registration number of the user submitting KYC application', max_length=255, null=True, verbose_name='Business Name Registration Number'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='email',
            field=models.EmailField(help_text='The primary e-mail address of the user submitting KYC application', max_length=150, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='kyc_country',
            field=models.ForeignKey(help_text='Country for which KYC has been performed against user. Each country may have different set of fields for KYC. This flag drives the system to show or hide the necessary fields.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_country', to='locations.country', verbose_name='KYC Country'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='legal_business_name',
            field=models.CharField(help_text='the business name of the user submitting KYC application', max_length=255, null=True, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='legal_first_names',
            field=models.CharField(help_text='First name of the user submitting KYC application - As shown in documents.', max_length=255, null=True, verbose_name='Legal First names'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='legal_last_names',
            field=models.CharField(help_text='First name of the user submitting KYC application - As shown in documents.', max_length=255, null=True, verbose_name='Legal Last names'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='user',
            field=models.ForeignKey(help_text='Unique identifier of the user that owns the activity.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='KYC User'),
        ),
    ]
