# Generated by Django 3.2.9 on 2022-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_kyc', '0011_auto_20220226_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='business_email',
            field=models.EmailField(help_text='The primary e-mail address of the user business submitting KYC application', max_length=150, null=True, verbose_name='Email Address'),
        ),
    ]
