# Generated by Django 3.2.9 on 2022-07-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_language'),
        ('kroon_kyc', '0013_auto_20220314_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='kyc_country',
            field=models.ForeignKey(blank=True, help_text='Country for which KYC has been performed against user. Each country may have different set of fields for KYC. This flag drives the system to show or hide the necessary fields.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_country', to='locations.country', verbose_name='KYC Country'),
        ),
        migrations.AlterField(
            model_name='marchantkycapplication',
            name='kyc_country',
            field=models.ForeignKey(help_text='Country for which KYC has been performed against user. Each country may have different set of fields for KYC. This flag drives the system to show or hide the necessary fields.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_country', to='locations.country', verbose_name='KYC Country'),
        ),
    ]
