# Generated by Django 3.2.9 on 2022-12-06 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kroon_kyc', '0016_marchantkycapplication_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='legal_last_names',
            field=models.CharField(blank=True, help_text='Last name of the user submitting KYC application - As shown in documents.', max_length=255, null=True, verbose_name='Legal Last names'),
        ),
        migrations.CreateModel(
            name='KYC_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('wallet_id', models.CharField(blank=True, help_text='First name of the user submitting KYC application - As shown in documents.', max_length=255, null=True, verbose_name='Legal First names')),
                ('user', models.ForeignKey(blank=True, help_text='Unique identifier of the user that owns the activity.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='KYC User')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
    ]
