# Generated by Django 3.2.9 on 2022-01-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('category', models.CharField(help_text='this hold the category for the products the marchant will be uploading under this category', max_length=255, null=True, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, help_text='Slug field for the category which is auto generated when the category is been created', max_length=300, null=True, verbose_name='Category Slug')),
                ('active', models.BooleanField(default=True, help_text='this indicates whether the category is active or not', null=True, verbose_name='Active')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Add or Delete Category',
                'verbose_name_plural': 'Add or Delete Category',
            },
        ),
    ]
