# Generated by Django 3.2.9 on 2022-01-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_kiosk', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-created_date',), 'verbose_name': 'Merchant Cart', 'verbose_name_plural': 'Merchant Cart'},
        ),
    ]
