# Generated by Django 3.2.9 on 2023-04-26 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0006_auto_20221212_1021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Cert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('cert_number', models.CharField(blank=True, help_text='Cert number holds the id given to deactivating and activating a recurring payment', max_length=255, null=True, verbose_name='Certificate Number')),
                ('cert_bearer_first_name', models.CharField(blank=True, help_text='this indicates the name of the certificate owner ', max_length=255, null=True, verbose_name='Cert Bearer First Name')),
                ('cert_bearer_last_name', models.CharField(blank=True, help_text='this indicates the name of the certificate owner ', max_length=255, null=True, verbose_name='Cert Bearer Last Name')),
                ('date_of_completion', models.DateTimeField(blank=True, help_text='this indicates the date in which the user completes he or her training process', null=True, verbose_name='Date Of Completion')),
                ('traning_platform', models.CharField(blank=True, choices=[('kroon_app', 'Kroon app'), ('Kroon_kiosk', 'Kroon kiosk')], help_text='this indicates the platform that the user completed his or her training process', max_length=30, null=True, verbose_name='Traning Platform')),
                ('cert_bearer_country', models.ForeignKey(blank=True, help_text='this shows the country in which the certificate is issued', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='Cert Bearer Country')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_cert_worker', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Training Cert Info',
                'verbose_name_plural': 'Training Cert Info',
                'ordering': ('-created_date',),
            },
        ),
    ]
