# Generated by Django 3.2.9 on 2023-04-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20221212_1021'),
        ('training_cert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_cert',
            name='cert_bearer_country',
            field=models.ForeignKey(help_text='this shows the country in which the certificate is issued', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='Cert Bearer Country'),
        ),
        migrations.AlterField(
            model_name='training_cert',
            name='cert_bearer_first_name',
            field=models.CharField(help_text='this indicates the name of the certificate owner ', max_length=255, null=True, verbose_name='Cert Bearer First Name'),
        ),
        migrations.AlterField(
            model_name='training_cert',
            name='cert_bearer_last_name',
            field=models.CharField(help_text='this indicates the name of the certificate owner ', max_length=255, null=True, verbose_name='Cert Bearer Last Name'),
        ),
        migrations.AlterField(
            model_name='training_cert',
            name='date_of_completion',
            field=models.DateTimeField(help_text='this indicates the date in which the user completes he or her training process', null=True, verbose_name='Date Of Completion'),
        ),
        migrations.AlterField(
            model_name='training_cert',
            name='traning_platform',
            field=models.CharField(choices=[('kroon_app', 'Kroon app'), ('Kroon_kiosk', 'Kroon kiosk')], help_text='this indicates the platform that the user completed his or her training process', max_length=30, null=True, verbose_name='Traning Platform'),
        ),
    ]
