# Generated by Django 3.2.9 on 2022-05-28 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('business_name', models.CharField(help_text='the business name for the merchant user.', max_length=255, null=True, verbose_name='Business Name')),
                ('business_registration_number', models.CharField(blank=True, help_text='the business registration number for the merchant user.', max_length=255, null=True, verbose_name='Business Registeration Number')),
                ('business_contact', models.CharField(help_text='the business contact number that belong to the merchant business account', max_length=255, null=True, verbose_name='Business Contact')),
                ('business_address', models.CharField(help_text='the business address for the registered merchant business account.', max_length=255, null=True, verbose_name='Business Address')),
                ('business_owner_name', models.CharField(help_text='the section store the business owner name for the registered merchant business account', max_length=255, null=True, verbose_name='Business Owner Name')),
                ('business_owner_contact', models.CharField(help_text='the section store the business owner contact number for the registered merchant business account', max_length=255, null=True, verbose_name='Business Owner Contact Number')),
                ('business_owner_email', models.EmailField(help_text='the business owners email address', max_length=255, null=True, verbose_name='Business Owner Email')),
                ('business_type', models.CharField(choices=[('registered business', 'Registered Business'), ('sole trade', 'Sole Trade')], help_text='gthe merchant need to select the business type on which their business runs on.', max_length=255, null=True, verbose_name='Business Type')),
                ('years_of_operation', models.DateField(help_text='this show how many years on which the business has been running.', null=True, verbose_name='Years Of Operation')),
                ('number_of_employees', models.IntegerField(default=0, help_text='the total number of employees that are currently working with', null=True, verbose_name='Numbers Of Employee')),
                ('period_of_report', models.CharField(choices=[('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('8 Months', '8 Months'), ('9 Months', '9 Months'), ('10 Months', '10 Months'), ('11 Months', '11 Months'), ('12 Months', '12 Months')], help_text='Select the how mnay months report you want to generate for your business', max_length=255, null=True, verbose_name='Period Of Report')),
                ('user', models.ForeignKey(help_text='The user for whom the business plan will be created for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_business_plan', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Merchant Business Plan',
                'verbose_name_plural': 'Merchant Business Plan',
                'ordering': ('-created_date',),
            },
        ),
    ]
