# Generated by Django 3.2.9 on 2022-05-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='business_name',
            field=models.ImageField(blank=True, help_text='Here goes your business logo in any (Optional).', null=True, upload_to='', verbose_name='Business Logo'),
        ),
        migrations.AlterField(
            model_name='business_plan',
            name='period_of_report',
            field=models.CharField(choices=[('1', '1 Month'), ('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('5', '5 Months'), ('6', '6 Months'), ('7', '7 Months'), ('8', '8 Months'), ('9', '9 Months'), ('10', '10 Months'), ('11', '11 Months'), ('12', '12 Months')], help_text='Select the how mnay months report you want to generate for your business', max_length=255, null=True, verbose_name='Period Of Report'),
        ),
    ]
