# Generated by Django 3.2.9 on 2022-05-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0002_auto_20220528_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='business_name',
            field=models.ImageField(blank=True, help_text='Here goes your business logo if any (Optional).', null=True, upload_to='', verbose_name='Business Logo'),
        ),
    ]
