# Generated by Django 3.2.9 on 2022-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0003_alter_business_plan_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_plan',
            name='business_logo',
            field=models.ImageField(blank=True, help_text='Here goes your business logo if any (Optional).', null=True, upload_to='', verbose_name='Business Logo'),
        ),
        migrations.AlterField(
            model_name='business_plan',
            name='business_name',
            field=models.CharField(help_text='the business name for the merchant user.', max_length=255, null=True, verbose_name='Business Name'),
        ),
    ]
