# Generated by Django 3.2.9 on 2022-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0004_auto_20220528_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='business_logo',
            field=models.ImageField(blank=True, help_text='Here goes your business logo if any ( Optional ).', null=True, upload_to='', verbose_name='Business Logo'),
        ),
        migrations.AlterField(
            model_name='business_plan',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='the business registration number for the merchant user ( Optional ).', max_length=255, null=True, verbose_name='Business Registeration Number'),
        ),
    ]
