# Generated by Django 3.2.9 on 2022-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0006_rename_years_of_operation_business_plan_year_of_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='year_of_operation',
            field=models.CharField(help_text='this show how many years on which the business has been running.', max_length=255, null=True, verbose_name='Years Of Operation'),
        ),
    ]
