# Generated by Django 3.2.9 on 2022-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0008_auto_20220529_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='data',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the initiated amount you paid for internet data bills monthly.', max_digits=300, null=True, verbose_name='Internet Data Bill'),
        ),
        migrations.AlterField(
            model_name='business_plan',
            name='electricity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the initiated amount you paid for electricity bill monthly.', max_digits=300, null=True, verbose_name='Electricity Bills'),
        ),
        migrations.AlterField(
            model_name='business_plan',
            name='fuel',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the initiated amount you paid for fuel monthly.', max_digits=300, null=True, verbose_name='Fuel Bill'),
        ),
        migrations.AlterField(
            model_name='business_plan',
            name='salaries',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the amount of salary that your workers is been paid monthly', max_digits=300, null=True, verbose_name='Salaries'),
        ),
    ]
