# Generated by Django 3.2.9 on 2022-05-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_categories', '0001_initial'),
        ('kiosk_business_plan', '0010_auto_20220530_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='business_type',
            field=models.ManyToManyField(help_text='Business category will refrence the  category  which your business falls into.', to='kiosk_categories.Category', verbose_name='Business category'),
        ),
    ]
