# Generated by Django 3.2.9 on 2022-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_categories', '0001_initial'),
        ('kiosk_business_plan', '0011_alter_business_plan_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_plan',
            name='business_category',
            field=models.ManyToManyField(help_text='Business category will refrence the  category  which your business falls into.', to='kiosk_categories.Category', verbose_name='Business category'),
        ),
        migrations.RemoveField(
            model_name='business_plan',
            name='business_type',
        ),
        migrations.AddField(
            model_name='business_plan',
            name='business_type',
            field=models.CharField(choices=[('registered business', 'Registered Business'), ('sole trade', 'Sole Trade')], help_text='gthe merchant need to select the business type on which their business runs on.', max_length=255, null=True, verbose_name='Business Type'),
        ),
    ]
