# Generated by Django 3.2.9 on 2022-06-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0014_alter_business_plan_period_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='salaries',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the amount of salary that a worker is been paid monthly', max_digits=300, null=True, verbose_name='Salaries'),
        ),
    ]
