# Generated by Django 3.2.9 on 2022-07-28 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk_business_plan', '0015_alter_business_plan_salaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_plan',
            name='user',
            field=models.ForeignKey(help_text='The user for whom the business plan will be created for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_business_plan', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
