# Generated by Django 3.2.9 on 2023-04-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_business_plan', '0017_businessplanexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_plan',
            name='business_expenses',
            field=models.ForeignKey(help_text='this is the business Expenses that is link to the expenses .', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_business_Expenses_profile', to='kiosk_business_plan.businessplanexpenses', verbose_name='Business Expenses'),
        ),
    ]
