# Generated by Django 3.2.9 on 2023-05-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulate_account',
            name='completed',
            field=models.BooleanField(default=False, help_text='this indicates whether the action is completed successfully', null=True, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='simulate_account',
            name='processing_status',
            field=models.BooleanField(default=False, help_text='this indicates whether the action is processing status successfully', null=True, verbose_name='processing status'),
        ),
    ]
