# Generated by Django 3.2.9 on 2023-05-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulation', '0002_auto_20230515_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulate_account',
            name='user',
            field=models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simuator_onboarding_user', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
