# Generated by Django 3.2.9 on 2023-05-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_simulate_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulate_account',
            name='action_count',
            field=models.IntegerField(help_text='this stores the account creation count.', null=True, verbose_name='Action Count'),
        ),
    ]
