# Generated by Django 3.2.9 on 2023-05-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_simulate_account_action_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulate_account',
            name='action_count',
            field=models.IntegerField(default=0, help_text='this stores the account creation count.', null=True, verbose_name='Action Count'),
        ),
    ]
