# Generated by Django 3.2.9 on 2022-12-06 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding_Users_CSV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('on_boarding_user_file', models.FileField(blank=True, help_text='csv format file which is used for the onboarding of uses by the gov user profile ', null=True, upload_to='onboarding_users/', verbose_name='Onboarding User File')),
                ('on_boarding_complete', models.BooleanField(default=False, help_text='Flag to determine if customer has completed onboarding process.', verbose_name='Completed Onboarding')),
                ('on_boarding_complete_date', models.DateTimeField(blank=True, help_text='Timestamp when customer completed onboarding process.', null=True, verbose_name='Onboarding Complete Date')),
                ('on_boarding_user', models.ForeignKey(blank=True, help_text='this is the gov user account that provides the current user information for on boarding', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_users', to=settings.AUTH_USER_MODEL, verbose_name='Gov Profile')),
            ],
            options={
                'verbose_name': 'Onboarding CSV Format',
                'verbose_name_plural': 'Onboarding CSV Format',
                'ordering': ('-created_date',),
            },
        ),
    ]
