# Generated by Django 3.2.9 on 2022-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding_users_csv',
            name='on_boarding_user_file',
            field=models.FileField(help_text='csv format file which is used for the onboarding of uses by the gov user profile ', null=True, upload_to='onboarding_users/', verbose_name='Onboarding User File'),
        ),
    ]
