# Generated by Django 3.2.9 on 2023-01-13 15:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gov_panel', '0002_alter_onboarding_users_csv_on_boarding_user_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convertion_Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('default_currency', models.CharField(default='USD', help_text='the default converted currency is saved , this record is been fetched from the default call', max_length=20, verbose_name='Default Currency')),
                ('local_currency', models.CharField(help_text='the local currency will be used during the conversion process', max_length=20, verbose_name='Local Currency')),
                ('default_currency_convetion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text=' this record holds the default currency conversion rate which will be updated .', max_digits=300, verbose_name='Default Currency Convetion Rate')),
                ('local_currency_convetion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text=' this record holds the local currency conversion rate which will be updated .', max_digits=300, verbose_name='Local Currency Convetion Rate')),
            ],
            options={
                'verbose_name': 'Convertion Rate',
                'verbose_name_plural': 'Convertion Rate',
                'ordering': ('-created_date',),
            },
        ),
    ]
