# Generated by Django 3.2.9 on 2023-02-14 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gov_panel', '0003_convertion_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_logs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('action', models.CharField(blank=True, help_text='Actions holds the current user intractions with the gov dashboard.', max_length=255, null=True, verbose_name='Actions')),
                ('user', models.ForeignKey(blank=True, help_text='this is the gov user account that provides the current user information for on boarding', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Gov Worker Profile')),
            ],
            options={
                'verbose_name': 'Worker Action Log',
                'verbose_name_plural': 'Worker Action Log',
                'ordering': ('-created_date',),
            },
        ),
    ]
