# Generated by Django 3.2.9 on 2023-02-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov_panel', '0004_action_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convertion_Rate',
        ),
    ]
