# Generated by Django 4.2.3 on 2023-08-07 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0006_government_organizations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="government_organizations",
            old_name="government_organization_name",
            new_name="government_organization",
        ),
    ]
