# Generated by Django 4.2.3 on 2023-08-07 23:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0008_alter_government_organizations_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="government_organizations",
            options={
                "ordering": ("-created_date",),
                "verbose_name": "Government Organizations",
                "verbose_name_plural": "Government Organizations",
            },
        ),
        migrations.AddField(
            model_name="government_organizations",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created.",
                max_length=20,
                verbose_name="Created Date",
            ),
        ),
        migrations.AddField(
            model_name="government_organizations",
            name="modified_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Modified date when the record was created.",
                max_length=20,
                verbose_name="Modified Date",
            ),
        ),
    
    ]
