# Generated by Django 4.2.3 on 2023-08-07 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0115_remove_user_government_organization_and_more"),
        ("gov_panel", "0009_alter_government_organizations_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Government_Organizations",
        ),
    ]
