# Generated by Django 4.2.3 on 2023-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0011_government_organizations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="government_organizations",
            name="government_organization",
            field=models.CharField(
                blank=True,
                help_text="The government organization name holds the title name of the organisation that the merchant business is registered under",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Government Organization Name",
            ),
        ),
    ]
