# Generated by Django 4.2.3 on 2023-08-10 12:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0014_alter_surveyqa_survey_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSurveyQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "survey_question",
                    models.CharField(
                        blank=True,
                        help_text="this shows rthe question of the survey",
                        max_length=255,
                        null=True,
                        verbose_name="Survey Questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Survey Question",
                "verbose_name_plural": "App Surveys Question",
            },
        ),
    ]
