# Generated by Django 4.2.3 on 2023-08-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0015_appsurveyquestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyqa",
            name="survey_question",
        ),
        migrations.AddField(
            model_name="surveyqa",
            name="survey_questions_id",
            field=models.ForeignKey(
                help_text="this hold the survey question ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_field",
                to="gov_panel.appsurveyquestion",
                verbose_name="Survey QA",
            ),
        ),
    ]
