# Generated by Django 4.2.3 on 2023-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0016_remove_surveyqa_survey_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsurveyquestion",
            name="survey_title",
            field=models.CharField(
                blank=True,
                help_text="this shows rthe question of the survey",
                max_length=255,
                null=True,
                verbose_name="Survey Title",
            ),
        ),
    ]
