# Generated by Django 4.2.3 on 2023-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0017_appsurveyquestion_survey_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsurveyquestion",
            name="survey_title",
        ),
        migrations.AddField(
            model_name="appsurveyquestion",
            name="surveys_title",
            field=models.CharField(
                blank=True,
                help_text="this shows the tittle of the survey",
                max_length=253,
                null=True,
                verbose_name="Survey Titles",
            ),
        ),
    ]
