# Generated by Django 4.2.3 on 2023-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0018_remove_appsurveyquestion_survey_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsurveyquestion",
            name="surveys_title",
        ),
        migrations.AddField(
            model_name="appsurveyquestion",
            name="surveys_titles",
            field=models.CharField(
                blank=True,
                help_text="this shows the tittle of the survey",
                max_length=300,
                null=True,
                verbose_name="Survey Titles",
            ),
        ),
        migrations.AlterField(
            model_name="appsurveyquestion",
            name="survey_question",
            field=models.CharField(
                blank=True,
                help_text="this shows rthe question of the survey",
                max_length=300,
                null=True,
                verbose_name="Survey Questions",
            ),
        ),
        migrations.AlterField(
            model_name="surveyqa",
            name="survey_answer",
            field=models.CharField(
                blank=True,
                help_text="the hold the answer of the survey",
                max_length=300,
                null=True,
                verbose_name="Survey Answer",
            ),
        ),
    ]
