# Generated by Django 4.2.3 on 2023-08-10 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0019_remove_appsurveyquestion_surveys_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsurveyquestion",
            name="surveys_titles",
        ),
    ]
