# Generated by Django 4.2.3 on 2023-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0020_remove_appsurveyquestion_surveys_titles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyqa",
            name="survey_qa",
        ),
        migrations.RemoveField(
            model_name="surveyqa",
            name="survey_questions_id",
        ),
        migrations.DeleteModel(
            name="App_Survey",
        ),
        migrations.DeleteModel(
            name="AppSurveyQuestion",
        ),
        migrations.DeleteModel(
            name="SurveyQA",
        ),
    ]
