# Generated by Django 3.2.9 on 2021-12-18 00:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('ad_name', models.CharField(help_text='this hold the name of the current ad', max_length=250, null=True, verbose_name='Ad Name')),
                ('ad_image', models.ImageField(help_text='input ad image which will be JPEG, PNG, or GIF', max_length=250, null=True, upload_to='', verbose_name='Ad Image')),
                ('ad_url', models.URLField(blank=True, help_text='link that redirect the user to the ad page, its optional.', null=True, verbose_name='Ad URL')),
                ('minimum_age', models.PositiveBigIntegerField(help_text='minimum view age determines the viewer minimum age.', null=True, verbose_name='Minimum Ad Viewer Age')),
                ('maximum_age', models.PositiveBigIntegerField(help_text='maximum view age determines the viewer minimum age.', null=True, verbose_name='Maximum Ad Viewer Age')),
                ('active', models.BooleanField(default=False, help_text='this status determines whether the ad is active or not to be viewed by users', null=True, verbose_name='Active Ad')),
            ],
            options={
                'verbose_name': 'Kroon Ads',
                'verbose_name_plural': 'Kroon Ads',
                'ordering': ('-created_date',),
            },
        ),
    ]
