# Generated by Django 3.2.9 on 2022-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_accept_kroon'),
        ('ads', '0002_ads_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ad_country',
            field=models.ManyToManyField(help_text=' this is the country that will be able to see this ad image', null=True, to='locations.Country'),
        ),
    ]
