# Generated by Django 3.2.9 on 2022-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_accept_kroon'),
        ('ads', '0003_ads_ad_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_country',
            field=models.ManyToManyField(help_text=' this is the country that will be able to see this ad image', to='locations.Country'),
        ),
    ]
