# Generated by Django 3.2.9 on 2022-04-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_ad_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='minimum_age',
        ),
    ]
