# Generated by Django 3.2.9 on 2022-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20220405_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='the gender that is allowed to view this ad', max_length=8, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='ads',
            name='maximum_age',
            field=models.PositiveBigIntegerField(help_text='maximum view age determines the viewer minimum age.', null=True, verbose_name='Maximum Ad Viewer Age'),
        ),
        migrations.AddField(
            model_name='ads',
            name='minimum_age',
            field=models.PositiveBigIntegerField(help_text='minimum view age determines the viewer minimum age.', null=True, verbose_name='Minimum Ad Viewer Age'),
        ),
    ]
