# Generated by Django 3.2.9 on 2022-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20220406_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='active',
            field=models.BooleanField(blank=True, default=False, help_text='this status determines whether the ad is active or not to be viewed by users', null=True, verbose_name='Active Ad'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='the gender that is allowed to view this ad', max_length=8, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='maximum_age',
            field=models.PositiveBigIntegerField(blank=True, help_text='maximum view age determines the viewer minimum age.', null=True, verbose_name='Maximum Ad Viewer Age'),
        ),
    ]
