# Generated by Django 3.2.9 on 2022-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20220406_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='platform',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='the gender that is allowed to view this ad', max_length=8, null=True, verbose_name='Gender'),
        ),
    ]
