# Generated by Django 3.2.9 on 2022-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='platform',
            field=models.CharField(blank=True, choices=[('kroon', 'Kroon'), ('kiosk', 'Kiosk')], help_text='the gender that is allowed to view this ad', max_length=8, null=True, verbose_name='Ad Platform'),
        ),
    ]
