# Generated by Django 3.2.9 on 2022-08-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_ads_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='minimum_age',
        ),
    ]
