# Generated by Django 3.2.9 on 2023-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20221212_1021'),
        ('ads', '0014_alter_ads_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_country',
            field=models.ManyToManyField(help_text=' this is the country that will be able to see this ad image', to='locations.Country', verbose_name='Ad Country'),
        ),
    ]
