# Generated by Django 3.2.9 on 2022-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_product',
            name='merchant_local_currency',
            field=models.CharField(help_text='Merchant local currency is been saved for the current product', max_length=50, null=True, verbose_name='Merchant Local Currency'),
        ),
        migrations.AlterField(
            model_name='merchant_product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the product amount which will be store in local currency', max_digits=300, null=True, verbose_name='Amount In Kroon Token'),
        ),
    ]
