# Generated by Django 3.2.9 on 2022-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0002_auto_20220423_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_product',
            name='merchant_local_currency',
            field=models.CharField(blank=True, help_text='Merchant local currency is been saved for the current product', max_length=50, null=True, verbose_name='Merchant Local Currency'),
        ),
    ]
