# Generated by Django 3.2.9 on 2022-05-11 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0003_alter_merchant_product_merchant_local_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_product',
            name='charge_by_weight',
            field=models.BooleanField(blank=True, default=True, help_text='if this action is been ticked the product sale price will be used to calculate the product if only the customer is buying it by size which includes weight or kilogram.', null=True, verbose_name='Charge By Weight'),
        ),
        migrations.AddField(
            model_name='merchant_product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='the product cost amount which will be store in local currency', max_digits=300, null=True, verbose_name='Cost Amount In Local Currency'),
        ),
        migrations.AlterField(
            model_name='merchant_product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image for the current product, which should be with no logo or trademark', null=True, upload_to='photos/products', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='merchant_product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, help_text='Product availablity for this is item is been activated to false when the stock is less than 1 or activated to true when the stcok is greater than one', null=True, verbose_name='Product availablity'),
        ),
        migrations.AlterField(
            model_name='merchant_product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='the product amount which will be store in local currency', max_digits=300, null=True, verbose_name='Amount In Local Currency'),
        ),
        migrations.AlterField(
            model_name='merchant_product',
            name='product_sku',
            field=models.CharField(blank=True, help_text='Product sku should be added which identify each product', max_length=500, null=True, verbose_name='Product SKU'),
        ),
        migrations.AlterField(
            model_name='merchant_product',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Total Product availablity for the current item , which will automatically be tagged as out of stock when it reduces to zero.', null=True, verbose_name='Total Stock'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('variations_category', models.CharField(choices=[('Color', 'Color'), ('Size', 'Size')], help_text='Select which variation category to the current product', max_length=255, null=True, verbose_name='Variations')),
                ('variation_value', models.CharField(help_text='the value to select for the variation product', max_length=250, null=True, verbose_name='Variation Value')),
                ('is_active', models.BooleanField(default=True, help_text='Status to dectect if the product variation is active or not', null=True, verbose_name='Variation Status')),
                ('product', models.ForeignKey(help_text='Product name refering to the product already uplaoded and to be added some variatons.', null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk_stores.merchant_product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Product Variation ',
                'verbose_name_plural': 'Product Variation',
                'ordering': ('-created_date',),
            },
        ),
    ]
