# Generated by Django 3.2.9 on 2022-05-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0004_auto_20220511_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Status to dectect if the product variation is active or not', null=True, verbose_name='Variation Status'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(help_text='Product name refering to the product already uplaoded and to be added some variatons.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_variation', to='kiosk_stores.merchant_product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation_value',
            field=models.CharField(blank=True, help_text='the value to select for the variation product', max_length=250, null=True, verbose_name='Variation Value'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variations_category',
            field=models.CharField(blank=True, choices=[('Color', 'Color'), ('Size', 'Size')], help_text='Select which variation category to the current product', max_length=255, null=True, verbose_name='Variations'),
        ),
    ]
