# Generated by Django 3.2.9 on 2022-05-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0005_auto_20220512_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='quantity',
            field=models.CharField(blank=True, help_text='the value holds the quantity for the product variation which will be deducated when ever the product is been added to cart and will also have a status of low qunatity, when ever its been out of stock.', max_length=250, null=True, verbose_name='Quantity'),
        ),
    ]
