# Generated by Django 3.2.9 on 2022-05-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0006_productvariation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='the value holds the quantity for the product variation which will be deducated when ever the product is been added to cart and will also have a status of low qunatity, when ever its been out of stock.', null=True, verbose_name='Quantity'),
        ),
    ]
