# Generated by Django 3.2.9 on 2022-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0007_alter_productvariation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, help_text='Total Product availablity for the current item , which will automatically be tagged as out of stock when it reduces to zero.', null=True, verbose_name='Total Stock'),
        ),
    ]
