# Generated by Django 3.2.9 on 2022-06-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_categories', '0001_initial'),
        ('kiosk_stores', '0010_productvariation_weight_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category will refrence the product category table which when the category is been deleted the items related to the parent or child category will be deleted as well.', null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk_categories.category', verbose_name='Product category'),
        ),
    ]
