# Generated by Django 3.2.9 on 2022-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0013_merchant_product_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_product',
            name='weight_unit',
            field=models.CharField(blank=True, default='KG', help_text='product weight unit i smeant to be inputed by the merchant or the product uploader.', max_length=50, null=True, verbose_name='Weight Unit'),
        ),
    ]
