# Generated by Django 3.2.9 on 2022-06-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0014_alter_merchant_product_weight_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant_product',
            old_name='weight_unit',
            new_name='product_weight_unit',
        ),
    ]
