# Generated by Django 3.2.9 on 2022-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0017_alter_merchant_product_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_product',
            name='low_stock',
            field=models.CharField(blank=True, help_text='this input store the stock limitation by which the merchant gets notified about his or low sotck level', max_length=50, null=True, verbose_name='Low Stock Limit'),
        ),
        migrations.AddField(
            model_name='merchant_product',
            name='out_of_stock_notify',
            field=models.BooleanField(blank=True, default=False, help_text='the true or false button identifies to the customer is he or she want to be notified when the stock is below the a given number ', null=True, verbose_name='Out Of Stock Notify'),
        ),
    ]
