# Generated by Django 3.2.9 on 2022-06-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0018_auto_20220613_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant_product',
            old_name='low_stock',
            new_name='low_stock_limit',
        ),
    ]
