# Generated by Django 3.2.9 on 2022-07-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0019_rename_low_stock_merchant_product_low_stock_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_product',
            name='image',
            field=models.ImageField(blank=True, default='images/empty.jpg', help_text='Product image for the current product, which should be with no logo or trademark', null=True, upload_to='photos/products', verbose_name='Product Image'),
        ),
    ]
