# Generated by Django 3.2.9 on 2022-08-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_alter_businessprofile_active'),
        ('kiosk_stores', '0025_alter_merchant_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_product',
            name='business_profile',
            field=models.ForeignKey(blank=True, help_text='This is the business profile associated with the product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_accounts', to='users.businessprofile', verbose_name='Business Profile'),
        ),
    ]
