# Generated by Django 4.2.5 on 2023-10-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk_stores", "0027_alter_merchant_product_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant_product",
            name="expire_notify",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="this indicates if the expiration notification will be sent to the merchant ",
                null=True,
                verbose_name="Expire Notification",
            ),
        ),
        migrations.AddField(
            model_name="merchant_product",
            name="expiring_date",
            field=models.DateField(
                blank=True,
                help_text="this storess the product expiring date and from which the merchant will be notified",
                max_length=50,
                null=True,
                verbose_name="Expiring Date",
            ),
        ),
    ]
