# Generated by Django 4.2.5 on 2023-11-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk_stores", "0028_merchant_product_expire_notify_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant_product",
            name="expiry_days_notify",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="This shows the days before the expiring date for the merchant to get the push notifications",
                null=True,
                verbose_name="Expiry Days",
            ),
        ),
    ]
