# Generated by Django 3.2.9 on 2022-03-20 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask_Statement_Of_Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('masked_id', models.CharField(help_text='this masked the user information to the public, to prevent crosssite scripting, note this is will be temporal.', max_length=255, null=True, verbose_name='Masked User Profile')),
                ('start_date', models.DateField(help_text='this specified the start date of the statement of account', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='this specified the end date of the statement of account', null=True, verbose_name='End Date')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Masked Statement Of Account',
                'verbose_name_plural': 'Masked Statement Of Account',
                'ordering': ('-created_date',),
            },
        ),
    ]
