# Generated by Django 3.2.9 on 2022-10-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_virtual_cards',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text=' This is the date of birth of the cardholder. Expected date format is YYYY/MM/DD. ', null=True, verbose_name='Date of Birth'),
        ),
    ]
