# Generated by Django 3.2.9 on 2022-10-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0002_alter_create_virtual_cards_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_virtual_cards',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], help_text=" This is the cardholder's gender. Expected values are M and F. ", max_length=70, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='create_virtual_cards',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], help_text=' This is title of the cardholder. Expected values are Mr, Mrs and Miss ', max_length=70, null=True, verbose_name='Title'),
        ),
    ]
