# Generated by Django 3.2.9 on 2022-10-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0003_auto_20221004_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_virtual_cards',
            name='billing_state',
            field=models.CharField(blank=True, help_text=' This is the State/County/Province/Region registered with the card. It is a two letter word representing the state in the billing country e.g CA, NY  ', max_length=50, null=True, verbose_name='Billing State'),
        ),
    ]
