# Generated by Django 3.2.9 on 2022-10-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtual_cards', '0005_virtual_cards_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Cards_Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('transactional_id', models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=355, null=True, verbose_name='Transactional ID')),
                ('card_id', models.CharField(blank=True, help_text=' This is the card identification number which is unique for each user virtual card  ', max_length=50, null=True, verbose_name='Card ID')),
                ('flw_ref', models.CharField(blank=True, editable=False, help_text='the theird party ref is the transactional ref which is generated by kroon topup third party.', max_length=355, null=True, verbose_name='Third Party Ref')),
                ('gateway_reference', models.CharField(blank=True, editable=False, help_text='the transaction gateway reference , which is provided to specify the card transactions ', max_length=355, null=True, verbose_name='Gateway Reference')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Amount In Kroon Token')),
                ('amount_in_localcurrency', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Amount In Local Currency')),
                ('currency', models.CharField(help_text='Transactional currency message that was taken by the customer.', max_length=300, null=True, verbose_name='Kroon Currency')),
                ('local_currency', models.CharField(help_text='Transactional currency message that was taken by the customer.', max_length=300, null=True, verbose_name='User Local Currency')),
                ('amount_settled', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='the final amount settled by the third providers , note this takes place when they have reducted their trasaction charges.', max_digits=300, null=True, verbose_name='Amount Settled')),
                ('debited_kroon_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='debited amount taken by the customer.', max_digits=300, null=True, verbose_name='Debited Amount')),
                ('credited_kroon_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='created amount taken by the customer.', max_digits=300, null=True, verbose_name='Credited Amount')),
                ('kroon_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='the remaining kroon balance amount taken for the customer.', max_digits=300, null=True, verbose_name='Kroon Balance')),
                ('payment_type', models.CharField(blank=True, help_text='the payment type which will be provided by the third party after the transaction has been approved.', max_length=300, null=True, verbose_name='Payment Type')),
                ('narration', models.CharField(help_text='Transactions message that was taken by the customer.', max_length=300, null=True, verbose_name='Transaction Message')),
                ('device_fingerprint', models.CharField(blank=True, help_text='the device finger print will be provided by kroon third party , note this is an optional field', max_length=300, null=True, verbose_name='Device Fingerprint')),
                ('transactional_date', models.DateTimeField(blank=True, help_text='the transactional date which holds the date the transaction was taken by our third party providers.', null=True, verbose_name='Transactional Date')),
                ('action', models.CharField(help_text='action status for the current transaction.', max_length=300, null=True, verbose_name='Action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('successful', 'Successful'), ('processing', 'Processing'), ('failed', 'failed')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status')),
                ('benefactor', models.ForeignKey(blank=True, help_text='The benefactor profile that sends the money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_card_trans_benefactor', to=settings.AUTH_USER_MODEL, verbose_name='Benefactor Profile')),
                ('recipient', models.ForeignKey(blank=True, help_text='The user profiles which recieves the transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_card_trans_reciever', to=settings.AUTH_USER_MODEL, verbose_name='Recipient Profile')),
                ('user', models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_virtual_card_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'All Transactions',
                'verbose_name_plural': 'All Transactions',
                'ordering': ['-created_date'],
            },
        ),
    ]
