# Generated by Django 3.2.9 on 2022-10-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0006_all_cards_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_Virtual_Cards',
        ),
    ]
