# Generated by Django 3.2.9 on 2022-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0008_virtual_cards_details_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_cards_transactions',
            old_name='credited_kroon_amount',
            new_name='credited_amount',
        ),
        migrations.RenameField(
            model_name='all_cards_transactions',
            old_name='debited_kroon_amount',
            new_name='debited_amount',
        ),
        migrations.RemoveField(
            model_name='all_cards_transactions',
            name='amount_in_localcurrency',
        ),
        migrations.RemoveField(
            model_name='all_cards_transactions',
            name='amount_settled',
        ),
        migrations.RemoveField(
            model_name='all_cards_transactions',
            name='benefactor',
        ),
        migrations.RemoveField(
            model_name='all_cards_transactions',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='all_cards_transactions',
            name='kroon_balance',
        ),
        migrations.RemoveField(
            model_name='all_cards_transactions',
            name='local_currency',
        ),
        migrations.RemoveField(
            model_name='all_cards_transactions',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='all_cards_transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='the total amount of the virtual card ', max_digits=300, null=True, verbose_name='Amount '),
        ),
    ]
