# Generated by Django 3.2.9 on 2022-10-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0009_auto_20221005_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_cards_transactions',
            old_name='amount',
            new_name='balance',
        ),
    ]
