# Generated by Django 3.2.9 on 2022-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0010_rename_amount_all_cards_transactions_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual_cards_details',
            name='card_design',
            field=models.CharField(blank=True, choices=[('Design_1', 'Design_1'), ('Design_2', 'Design_2'), ('Design_3', 'Design_3'), ('Design_4', 'Design_4')], help_text=' This is the card design selected by the user   ', max_length=50, null=True, verbose_name='Card Design'),
        ),
    ]
