# Generated by Django 3.2.9 on 2021-12-14 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_auto_20211214_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='reciever',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='reciever', to=settings.AUTH_USER_MODEL, verbose_name='Reciever Profile'),
        ),
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='sender',
            field=models.ForeignKey(help_text='The user that is currently sending kroon token.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sender Profile'),
        ),
        migrations.CreateModel(
            name='KroonTokenRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('amount_in_kroon_token', models.PositiveIntegerField(help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Kroon Token')),
                ('wallet_id', models.CharField(default='MICHSJSDE', editable=False, help_text='Wallet ID that belongs to the customer, requesting a transaction', max_length=9, null=True, verbose_name='Wallet ID')),
                ('kroon_token_qrcode', models.ImageField(help_text='Token qrcode is been generated from the customer token request.', null=True, upload_to='token_barcode/', verbose_name='Kroon Token QR Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status')),
                ('request_user', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Request User Profile')),
                ('sender', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender User Profile')),
                ('transactional_id', models.ForeignKey(editable=False, help_text='Transaction identifier that belongs to the customer', null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transactions', verbose_name='Transactional ID')),
            ],
            options={
                'verbose_name': 'Token Request',
                'verbose_name_plural': 'Token Request',
                'ordering': ('created_date',),
            },
        ),
    ]
