# Generated by Django 3.2.9 on 2021-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20211214_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='wallet_id',
            field=models.CharField(editable=False, help_text='Wallet ID that belongs to the customer, requesting a transaction', max_length=9, null=True, verbose_name='Wallet ID'),
        ),
    ]
