# Generated by Django 3.2.9 on 2021-12-14 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_alter_kroontokenrequest_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender User Profile'),
        ),
    ]
