# Generated by Django 3.2.9 on 2021-12-14 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_kroontokenrequest_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kroontokenrequest',
            options={'ordering': ('-created_date',), 'verbose_name': 'Token Request', 'verbose_name_plural': 'Token Request'},
        ),
        migrations.AlterModelOptions(
            name='kroontokentransfer',
            options={'ordering': ('-created_date',), 'verbose_name': 'All Kroon Token Transfer', 'verbose_name_plural': 'All Kroon Token Transfer'},
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactional_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Transaction identifier that belongs to the customer', null=True, verbose_name='Transactional ID'),
        ),
    ]
