# Generated by Django 3.2.9 on 2021-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20211214_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='kroon_token_qrcode',
            field=models.ImageField(blank=True, help_text='Token qrcode is been generated from the customer token request.', null=True, upload_to='token_barcode/', verbose_name='Kroon Token QR Code'),
        ),
    ]
