# Generated by Django 3.2.9 on 2021-12-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_kroontokenrequest_kroon_token_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused'), ('recieved', 'Recieved')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=30, null=True, verbose_name='Transactional ID'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused'), ('recieved', 'Recieved')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=30, null=True, verbose_name='Transactional ID'),
        ),
    ]
