# Generated by Django 3.2.9 on 2021-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(default=100, help_text='Amount paid for the above order by the customer.', null=True, verbose_name='Amount Paid'),
        ),
    ]
