# Generated by Django 3.2.9 on 2021-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_ref',
            field=models.CharField(help_text='The payment identification number sent from the payment gateway.', max_length=50, null=True, verbose_name='Payment Ref No'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='payment status to identify if the payment is been verified by the payment gateway or not.', max_length=150, null=True, verbose_name='Payment Status'),
        ),
    ]
