# Generated by Django 3.2.9 on 2021-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_alter_transactionalpin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=30, null=True, verbose_name='Transactional ID'),
        ),
    ]
