# Generated by Django 3.2.9 on 2021-12-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_alter_kroontokentransfer_transactional_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(help_text='payment currency is the currency code for the user while making payment', max_length=4, null=True, verbose_name='Payment Currency'),
        ),
    ]
