# Generated by Django 3.2.9 on 2021-12-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_kroongift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kroongift',
            old_name='receiver',
            new_name='receiver_email',
        ),
        migrations.AddField(
            model_name='kroongift',
            name='transactional_pin',
            field=models.CharField(editable=False, help_text='Transaction pin that belongs ', max_length=6, null=True, verbose_name='Transactional Pin'),
        ),
    ]
