# Generated by Django 3.2.9 on 2021-12-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_alter_kroongift_transactional_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroongift',
            name='transactional_pin',
            field=models.CharField(help_text='Transaction pin that belongs ', max_length=100, null=True, verbose_name='Transactional Pin'),
        ),
    ]
