# Generated by Django 3.2.9 on 2021-12-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_kroongift_transactional_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(help_text='transaction type for the current operation', max_length=20, null=True, verbose_name='Transaction Type'),
        ),
    ]
