# Generated by Django 3.2.9 on 2022-01-19 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0025_transactions_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_date',), 'verbose_name': 'All Flutterwave Payment', 'verbose_name_plural': 'All Flutterwave Payment'},
        ),
        migrations.AlterField(
            model_name='kroongift',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.CreateModel(
            name='UserRequestToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('transactional_id', models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=30, null=True, verbose_name='Transactional ID')),
                ('amount_in_kroon_token', models.PositiveIntegerField(help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Kroon Token')),
                ('wallet_id', models.CharField(editable=False, help_text='Wallet ID that belongs to the customer, requesting a transaction', max_length=9, null=True, verbose_name='Wallet ID')),
                ('action', models.CharField(default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status')),
                ('request_user', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Request User Profile')),
                ('sender', models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kroon_sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender User Profile')),
            ],
            options={
                'verbose_name': 'Users Kroon Transfer',
                'verbose_name_plural': 'Users Kroon Transfer',
                'ordering': ('-created_date',),
            },
        ),
    ]
