# Generated by Django 3.2.9 on 2022-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_auto_20220119_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesttoken',
            name='action',
            field=models.CharField(default='user kroon token', editable=False, help_text='action status for the current transaction.', max_length=20, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='wallet_id',
            field=models.CharField(help_text='Wallet ID that belongs to the customer, requesting a transaction', max_length=9, null=True, verbose_name='Wallet ID'),
        ),
    ]
