# Generated by Django 3.2.9 on 2022-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_auto_20220119_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroongift',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='payment status to identify if the payment is been verified by the payment gateway or not.', max_length=150, null=True, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='amount_in_kroon_token',
            field=models.PositiveIntegerField(blank=True, help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('success', 'Success')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='transactional_id',
            field=models.CharField(help_text='Transaction identifier that belongs to the customer', max_length=30, null=True, verbose_name='Transactional ID'),
        ),
    ]
