# Generated by Django 3.2.9 on 2022-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_alter_transactions_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='message',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='action',
            field=models.CharField(help_text='Transactions actions that was taken by the customer.', max_length=300, null=True, verbose_name='Transaction Action'),
        ),
    ]
