# Generated by Django 3.2.9 on 2022-01-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_rename_reciever_kroontokentransfer_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='kroontokentransfer',
            name='action',
            field=models.CharField(default='KROON TRANSFER', editable=False, help_text='action status for the current transaction.', max_length=300, null=True, verbose_name='Action'),
        ),
    ]
