# Generated by Django 3.2.9 on 2022-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_auto_20220123_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='kroontokenrequest',
            name='action',
            field=models.CharField(default='KROON TOKEN REQUEST', editable=False, help_text='action status for the current transaction.', max_length=300, null=True, verbose_name='Action'),
        ),
    ]
