# Generated by Django 3.2.9 on 2022-01-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_alter_userrequesttoken_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=35, null=True, verbose_name='Transactional ID'),
        ),
    ]
