# Generated by Django 3.2.9 on 2022-02-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_auto_20220201_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(help_text='Transactional currency message that was taken by the customer.', max_length=300, null=True, verbose_name='Transaction Message'),
        ),
    ]
