# Generated by Django 3.2.9 on 2022-02-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_transactions_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=355, null=True, verbose_name='Transactional ID'),
        ),
    ]
