# Generated by Django 3.2.9 on 2022-02-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_alter_transactions_transactional_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kroontokenrequest',
            name='kroon_token_qrcode',
        ),
    ]
