# Generated by Django 3.2.9 on 2022-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_remove_kroontokenrequest_kroon_token_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroongift',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=255, null=True, verbose_name='Transactional ID'),
        ),
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='transactional_id',
            field=models.CharField(editable=False, help_text='Transaction identifier that belongs to the customer', max_length=255, null=True, verbose_name='Transactional ID'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='transactional_id',
            field=models.CharField(help_text='Transaction identifier that belongs to the customer', max_length=255, null=True, verbose_name='Transactional ID'),
        ),
    ]
