# Generated by Django 3.2.9 on 2022-02-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0049_auto_20220214_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KroonGift',
        ),
    ]
