# Generated by Django 3.2.9 on 2022-02-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0050_delete_kroongift'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_in_kroon',
            field=models.IntegerField(help_text='Amount paid for the above order by the customer.', null=True, verbose_name='Kroon Amount Paid'),
        ),
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='action',
            field=models.CharField(default='OPEN KROON REQUEST', editable=False, help_text='action status for the current transaction.', max_length=300, null=True, verbose_name='Action'),
        ),
    ]
