# Generated by Django 3.2.9 on 2022-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0054_alter_kroontokentransfer_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_in_localcurrency',
            field=models.FloatField(blank=True, help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Local Currency'),
        ),
    ]
