# Generated by Django 3.2.9 on 2022-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0055_transactions_amount_in_localcurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='local_currency',
            field=models.CharField(help_text='Transactional currency message that was taken by the customer.', max_length=300, null=True, verbose_name='User Local Currency'),
        ),
    ]
