# Generated by Django 3.2.9 on 2022-03-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0057_auto_20220302_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='amount_in_kroon_token',
            field=models.FloatField(default=0.0, help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='kroon_token',
            field=models.FloatField(default=0.0, help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0.0, help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount_in_localcurrency',
            field=models.FloatField(blank=True, default=0.0, help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Local Currency'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='amount_in_kroon_token',
            field=models.FloatField(blank=True, default=0.0, help_text='transactional amount taken by the customer.', null=True, verbose_name='Amount In Kroon Token'),
        ),
    ]
