# Generated by Django 3.2.9 on 2022-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0058_auto_20220302_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='amount_in_kroon_token',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=10, null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='kroon_token',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=10, null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=10, null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount_in_localcurrency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=10, null=True, verbose_name='Amount In Local Currency'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='amount_in_kroon_token',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=10, null=True, verbose_name='Amount In Kroon Token'),
        ),
    ]
