# Generated by Django 3.2.9 on 2022-03-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0059_auto_20220302_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_in_kroon',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for the above order by the customer.', max_digits=10, null=True, verbose_name='Kroon Amount Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for the above order by the customer.', max_digits=10, null=True, verbose_name='Amount Paid'),
        ),
    ]
