# Generated by Django 3.2.9 on 2022-03-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0060_auto_20220302_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='amount_in_kroon_token',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='kroon_token',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_in_kroon',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for the above order by the customer.', max_digits=300, null=True, verbose_name='Kroon Amount Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for the above order by the customer.', max_digits=300, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Amount In Kroon Token'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount_in_localcurrency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Amount In Local Currency'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='amount_in_kroon_token',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Amount In Kroon Token'),
        ),
    ]
