# Generated by Django 3.2.9 on 2022-03-15 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0062_auto_20220315_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='benefactor',
            field=models.ForeignKey(blank=True, help_text='The benefactor profile that sends the money', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trans_benefactor', to=settings.AUTH_USER_MODEL, verbose_name='Benefactor Profile'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='The user profiles which recieves the transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trans_reciever', to=settings.AUTH_USER_MODEL, verbose_name='Recipient Profile'),
        ),
    ]
