# Generated by Django 3.2.9 on 2022-03-21 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0065_auto_20220320_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
