# Generated by Django 3.2.9 on 2022-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0068_transactions_amount_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('successful', 'Successful'), ('failed', 'failed')], default='pending', help_text='payment status to identify if the payment is been verified by the payment gateway or not.', max_length=255, null=True, verbose_name='Payment Status'),
        ),
    ]
