# Generated by Django 3.2.9 on 2022-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0069_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settled',
            field=models.BooleanField(default=False, help_text='this indicates whether the payment is been settled or not.', null=True, verbose_name='Payment Settled'),
        ),
    ]
