# Generated by Django 3.2.9 on 2022-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0070_payment_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='billing_date',
            field=models.DateTimeField(blank=True, help_text='this stores the billing date and time of the customer during the transaction', max_length=255, null=True, verbose_name='Billing Date And Time'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='this stores the billing email of the customer', max_length=255, null=True, verbose_name='Billing Email'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='billing_id',
            field=models.CharField(blank=True, help_text='this is the identication number which for the current transaction.', max_length=255, null=True, verbose_name='Billing ID'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='billing_mobile_number',
            field=models.CharField(blank=True, help_text='this stores the billing mobile Number of the customer', max_length=255, null=True, verbose_name='Billing Mobile number'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='billing_name',
            field=models.CharField(blank=True, help_text='this stores the billing name of the customer, note this is the full name', max_length=255, null=True, verbose_name='Billing Name'),
        ),
    ]
