# Generated by Django 3.2.9 on 2022-04-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0074_transactions_service_providers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
