# Generated by Django 3.2.9 on 2022-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0075_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('successful', 'Successful'), ('processing', 'Processing'), ('failed', 'failed')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('successful', 'Successful'), ('processing', 'Processing'), ('failed', 'failed')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected/Refused'), ('received', 'Received'), ('successful', 'Successful'), ('processing', 'Processing'), ('failed', 'failed')], default='pending', help_text='action status for the current transaction, which determines if it successful or not.', max_length=20, null=True, verbose_name='Transaction Status'),
        ),
    ]
