# Generated by Django 3.2.9 on 2022-07-28 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0076_auto_20220625_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='recipient',
            field=models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recipient User Profile'),
        ),
        migrations.AlterField(
            model_name='kroontokenrequest',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender User Profile'),
        ),
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='recipient',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL, verbose_name='Recipient Profile'),
        ),
        migrations.AlterField(
            model_name='kroontokentransfer',
            name='sender',
            field=models.ForeignKey(help_text='The user that is currently sending kroon token.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender Profile'),
        ),
        migrations.AlterField(
            model_name='transactionalpin',
            name='user',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='benefactor',
            field=models.ForeignKey(blank=True, help_text='The benefactor profile that sends the money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_benefactor', to=settings.AUTH_USER_MODEL, verbose_name='Benefactor Profile'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='The user profiles which recieves the transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_reciever', to=settings.AUTH_USER_MODEL, verbose_name='Recipient Profile'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='recipient',
            field=models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Request User Profile'),
        ),
        migrations.AlterField(
            model_name='userrequesttoken',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kroon_sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender User Profile'),
        ),
    ]
