# Generated by Django 3.2.9 on 2022-06-04 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotional_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='government_promo_code',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotinoal_code_user', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
