# Generated by Django 3.2.9 on 2022-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotional_codes', '0002_government_promo_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='government_promo_code',
            name='yearly_code',
            field=models.BooleanField(blank=True, default=False, help_text='the indicates if the promo code is a yearly code or not', null=True, verbose_name='Yearly Code'),
        ),
    ]
