# Generated by Django 4.1.9 on 2023-06-05 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotional_codes", "0004_alter_government_promo_code_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount_Code",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True,
                        help_text="the discount code which applies a discount price to the  actual subscription",
                        max_length=255,
                        null=True,
                        verbose_name="Discount Code",
                    ),
                ),
                (
                    "used_code",
                    models.BooleanField(
                        default=False,
                        help_text="this hsows if the code is been used by another customer or already expired.",
                        null=True,
                        verbose_name="Used Code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user for whom account belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gov_discount_code_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount Code",
                "verbose_name_plural": "Discount Code",
                "ordering": ("-created_date",),
            },
        ),
    ]
