# Generated by Django 4.2.3 on 2023-08-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_alter_subscription_plan_slug_plan_name"),
        ("promotional_codes", "0005_discount_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="government_promo_code",
            name="code_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="the code plans represents the plan in which the promotional code will be linked to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="code_plans",
                to="subscriptions.subscription_plan",
            ),
        ),
    ]
