# Generated by Django 3.2.9 on 2021-12-10 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211210_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'All Registered customers', 'verbose_name_plural': 'All Registered customers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='available_balance',
            field=models.FloatField(blank=True, default=0, help_text='The customers available balance for the account', null=True, verbose_name='Available Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='crypto_available_balance',
            field=models.FloatField(blank=True, default=0, help_text='The customers available balance in crypto currency , converting the available balance to crypto currency', null=True, verbose_name='Crypto Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='crypto_referral_bonus',
            field=models.FloatField(blank=True, default=0, help_text='The customers withdrable balance in crypto converting the referral balance to crypto currency', null=True, verbose_name='Crypto Referral Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='crypto_withdrawal_balance',
            field=models.FloatField(blank=True, default=0, help_text='The customers withdrable balance in crypto converting the withdrawable balance to crypto currency', null=True, verbose_name='Crypto Withdrawal Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency_id',
            field=models.CharField(blank=True, default='USD', help_text='The default currency of the customer. Currency will be sent against customers country of residence.', max_length=3, null=True, verbose_name='Default Currency ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address of the customer.', max_length=150, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='The first nammes of the customer.', max_length=50, null=True, verbose_name='First names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the customer.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='The last nammes of the customer.', max_length=50, null=True, verbose_name='Last names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_bonus',
            field=models.FloatField(blank=True, default=0, help_text='The customers referral bonus balance for the account', null=True, verbose_name='Referral Bonus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='withdrawal_balance',
            field=models.FloatField(blank=True, default=0, help_text='The customers withdrable balance for the account', null=True, verbose_name='Withdrawal Balance'),
        ),
    ]
