# Generated by Django 3.2.9 on 2021-12-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211210_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_complete',
            field=models.BooleanField(blank=True, default=False, help_text='Flag to determine if a cutomer have completed KYC verification', null=True, verbose_name='KYC complete'),
        ),
    ]
