# Generated by Django 3.2.9 on 2021-12-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_kyc_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='crypto_available_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='crypto_referral_bonus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='crypto_withdrawal_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='withdrawal_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('marchant', 'Marchant'), ('organization', 'Organization')], default='borrower', help_text='Account type', max_length=15, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency_id',
            field=models.CharField(blank=True, default='NGN', help_text='The default currency of the customer. Currency will be sent against customers country of residence.', max_length=3, null=True, verbose_name='Default Currency ID'),
        ),
    ]
