# Generated by Django 3.2.9 on 2021-12-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211211_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the customer.', max_length=13, null=True, verbose_name='Contact number'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number_verified',
            field=models.BooleanField(blank=True, default=False, help_text='Flag to determine if a cutomer have completed Contact number verification', null=True, verbose_name='Contact Number Verification'),
        ),
    ]
