# Generated by Django 3.2.9 on 2021-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211211_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(help_text='The contact number of the customer.', max_length=13, null=True, unique=True, verbose_name='Contact number'),
        ),
    ]
