# Generated by Django 3.2.9 on 2021-12-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(help_text='the resisdent country of the customer', max_length=40, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(blank=True, help_text='User kroon wallet id is unique to every user, the wallet id contains information about the customer', max_length=20, null=True, unique=True, verbose_name='Kroon Wallet ID'),
        ),
    ]
