# Generated by Django 3.2.9 on 2021-12-13 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0011_auto_20211212_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='The Ip address recorded at the time if registeration.', null=True, verbose_name='Registered Ip Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=models.ForeignKey(blank=True, help_text='The country residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country of Residence'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the customer.', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('current', 'Current Address'), ('permanent', 'Permanent Address')], default='current', help_text='The type of address.', max_length=9, verbose_name='Address Type')),
                ('address_line_1', models.CharField(blank=True, help_text='Address line 1 of the user', max_length=50, null=True, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Address line 2 of the user', max_length=50, null=True, verbose_name='Address line 2')),
                ('state', models.CharField(blank=True, help_text='State or Region of the user', max_length=50, null=True, verbose_name='State or Region')),
                ('city', models.CharField(blank=True, help_text='The city of the address of the user.', max_length=50, null=True, verbose_name='City')),
                ('zip_post_code', models.CharField(blank=True, help_text='Zip post code of the user address', max_length=50, null=True, verbose_name='Zip Post Code')),
                ('country', models.ForeignKey(blank=True, help_text='Country of the user', null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country')),
                ('user', models.ForeignKey(help_text='The user for whom address belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Address',
            },
        ),
    ]
