# Generated by Django 3.2.9 on 2021-12-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_country_of_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(blank=True, help_text='The country residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.', max_length=50, null=True, verbose_name='Country of Residence'),
        ),
    ]
