# Generated by Django 3.2.9 on 2021-12-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211213_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_submitted',
            field=models.BooleanField(blank=True, default=False, help_text='Flag to determine if customer has submitted a KYC verification.', null=True, verbose_name='KYC submitted'),
        ),
    ]
