# Generated by Django 3.2.9 on 2021-12-16 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_kyc_submitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'Customers  Address', 'verbose_name_plural': 'Customers  Address'},
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserBankDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('account_name', models.CharField(help_text='the customers bank account name.', max_length=70, null=True, verbose_name='Account Name')),
                ('account_number', models.CharField(help_text='the customers bank account number for the bank', max_length=20, null=True, verbose_name='Account Number')),
                ('bank_name', models.CharField(help_text='The bank name of the customer.', max_length=60, null=True, verbose_name='Bank Name')),
                ('bank_code', models.PositiveIntegerField(help_text='The bankinig code which is required for the withdrawal.', null=True, verbose_name='Bank Code')),
                ('bank_id', models.PositiveIntegerField(help_text='The bankinig code which is required for the withdrawal.', null=True, verbose_name='Bank Code')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Customer Bank Details',
                'verbose_name_plural': 'Customer Bank Details',
                'ordering': ('-created_date',),
            },
        ),
    ]
