# Generated by Django 3.2.9 on 2021-12-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211216_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankdetails',
            name='verified',
            field=models.BooleanField(default=False, help_text='customers account verification status which determines whether the account number is verified or not .', null=True, verbose_name='Account Verified'),
        ),
    ]
