# Generated by Django 3.2.9 on 2021-12-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userbankdetails_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_code',
            field=models.CharField(help_text='The bankinig code which is required for the withdrawal.', max_length=3, null=True, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_id',
            field=models.CharField(help_text='The bankinig ID which is required for the withdrawal.', max_length=3, null=True, verbose_name='Bank ID'),
        ),
    ]
