# Generated by Django 3.2.9 on 2021-12-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211217_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(help_text='device ID give each customer a unique id which is required during registration', max_length=400, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(help_text='fire base token used to authenticate when ever a notification is been pushed', max_length=255, null=True, verbose_name='Fire Base Token'),
        ),
    ]
