# Generated by Django 3.2.9 on 2021-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211218_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(help_text='users gender should be input.', max_length=7, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('marchant', 'Marchant')], default='borrower', help_text='Account type', max_length=15, null=True, verbose_name='Account Type'),
        ),
    ]
