# Generated by Django 3.2.9 on 2021-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211218_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='users gender should be input.', max_length=7, null=True, verbose_name='Gender'),
        ),
    ]
