# Generated by Django 3.2.9 on 2021-12-24 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWrongPinValidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('failed_password', models.PositiveIntegerField(default=0, help_text='the user password fialed count which store the count for a user when ever the password fails.', null=True, verbose_name='Password Failed Count')),
                ('banned', models.BooleanField(default=False, verbose_name='Password Banned')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Password Fialed Count',
                'verbose_name_plural': 'Password Fialed Count',
                'ordering': ('-created_date',),
            },
        ),
    ]
