# Generated by Django 3.2.9 on 2021-12-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_opts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opts',
            name='duration',
            field=models.DateTimeField(help_text='duration of which the opt will be expired from been used ny the user , which a new opt will be sent to the user to obtain a new opt token.', null=True, verbose_name='Opt Duration'),
        ),
    ]
