# Generated by Django 3.2.9 on 2021-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_opts_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submitted_bank_details',
            field=models.BooleanField(default=False, help_text='this indicates whether the user has submitted his or har bank detail or not ,', null=True, verbose_name='Submitted Bank Details'),
        ),
    ]
