# Generated by Django 3.2.9 on 2022-01-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_submitted_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='opts',
            name='reason',
            field=models.CharField(choices=[('email verification', 'Email Verification'), ('phone number verification', 'Phone Number Verification'), ('change transactional pin', 'Change Transactional Pin')], help_text='reason for otp to be sent to the user to be allowed to perform his or her action.', max_length=60, null=True),
        ),
    ]
