# Generated by Django 3.2.9 on 2022-01-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_opts_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='opts',
            name='active',
            field=models.BooleanField(default=False, help_text='This status indicates whether otp is still active or not', null=True, verbose_name='OTP Active'),
        ),
    ]
