# Generated by Django 3.2.9 on 2022-01-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_opts_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opts',
            name='active',
            field=models.BooleanField(default=True, help_text='This status indicates whether otp is still active or not', null=True, verbose_name='OTP Active'),
        ),
    ]
