# Generated by Django 3.2.9 on 2022-01-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_opts_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opts',
            name='active',
            field=models.BooleanField(default=True, help_text='This status indicates whether otp is still active or not', null=True, verbose_name='OTP Active'),
        ),
        migrations.AlterField(
            model_name='opts',
            name='reason',
            field=models.CharField(choices=[('email verification', 'Email Verification'), ('phone number verification', 'Phone Number Verification'), ('change transactional pin', 'Change Transactional Pin')], help_text='reason for otp to be sent to the user to be allowed to perform his or her action.', max_length=60, null=True),
        ),
    ]
