# Generated by Django 3.2.9 on 2022-01-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20220106_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opts',
            name='reason',
        ),
    ]
