# Generated by Django 3.2.9 on 2022-01-06 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_opts_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opts',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='duration of which the opt will be expired from been used ny the user , which a new opt will be sent to the user to obtain a new opt token.', null=True, verbose_name='Opt Duration'),
        ),
    ]
