# Generated by Django 3.2.9 on 2022-01-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_opts_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': 'All Registered customers', 'verbose_name_plural': 'All Registered customers'},
        ),
    ]
