# Generated by Django 3.2.9 on 2022-01-13 22:20

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KroonTermsAndConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('content', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=False, help_text='this indicates whether the content should available for display or not ', null=True, verbose_name='Content Active')),
            ],
            options={
                'verbose_name': 'Kroon terms and conditions',
                'verbose_name_plural': 'Kroon terms and conditions',
                'ordering': ('-created_date',),
            },
        ),
    ]
