# Generated by Django 3.2.9 on 2022-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_kroontermsandconditions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroontermsandconditions',
            name='content',
            field=models.TextField(help_text='here goes the content for kroon terms and conditions', null=True, verbose_name='Content'),
        ),
    ]
