# Generated by Django 3.2.9 on 2022-01-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
