# Generated by Django 3.2.9 on 2022-01-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_delete_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OPTs',
        ),
    ]
