# Generated by Django 3.2.9 on 2022-02-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, help_text='The users address which can be business address or home address ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.useraddress', verbose_name='User Address'),
        ),
    ]
