# Generated by Django 3.2.9 on 2022-02-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20220203_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_details',
            field=models.ForeignKey(blank=True, help_text='The users bank details associated for the user local bank withdrawal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='users.userbankdetails', verbose_name='User Bank Details'),
        ),
    ]
