# Generated by Django 3.2.9 on 2022-02-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_user_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(auto_created=True, blank=True, help_text='Timestamp when customer completed KYC verifiction process.', null=True, verbose_name='KYC complete date'),
        ),
    ]
