# Generated by Django 3.2.9 on 2022-02-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_user_kyc_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed KYC verifiction process.', null=True, verbose_name='KYC complete date'),
        ),
    ]
