# Generated by Django 3.2.9 on 2022-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_userbankdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_code',
            field=models.CharField(help_text='The bankinig code which is required for the withdrawal.', max_length=25, null=True, verbose_name='Bank Code'),
        ),
    ]
