# Generated by Django 3.2.9 on 2022-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_userbankdetails_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(help_text='the device id is meant to be unique across all platform to identify for security reasons', max_length=255, null=True, verbose_name='Device ID'),
        ),
    ]
