# Generated by Django 3.2.9 on 2022-02-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(help_text='the device id is meant to be unique across all platform to identify for security reasons', max_length=455, null=True, verbose_name='Device ID'),
        ),
    ]
