# Generated by Django 3.2.9 on 2022-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_user_merchant_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='merchant_business_name',
            field=models.CharField(blank=True, help_text='merchant business name which will be saved when the merchant update or register their business account', max_length=255, null=True, verbose_name='Merchant Business Profile'),
        ),
    ]
