# Generated by Django 3.2.9 on 2022-03-08 18:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_alter_user_kroon_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAndCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('content', models.TextField(help_text='here goes the content for kroon terms and conditions', null=True, verbose_name='Content')),
                ('active', models.BooleanField(default=False, help_text='this indicates whether the content should available for display or not ', null=True, verbose_name='Content Active')),
            ],
            options={
                'verbose_name': 'Kroon Policy',
                'verbose_name_plural': 'Kroon Policy',
                'ordering': ('-created_date',),
            },
        ),
    ]
