# Generated by Django 3.2.9 on 2022-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20220314_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_money_detials_submitted',
            field=models.BooleanField(default=False, help_text='this indicates whether the user has submitted his or har mobile money detail or not ,', null=True, verbose_name='Submitted Mobile Money Details'),
        ),
    ]
