# Generated by Django 3.2.9 on 2022-03-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_user_mobile_money_detials_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_money_detials_submitted',
            new_name='mobile_money_details_submitted',
        ),
    ]
