# Generated by Django 3.2.9 on 2022-03-15 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_rename_mobile_money_detials_submitted_user_mobile_money_details_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created', verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified.', verbose_name='Modified Date'),
        ),
    ]
