# Generated by Django 3.2.9 on 2022-03-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20220315_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='user',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
