# Generated by Django 3.2.9 on 2022-03-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_alter_userbankdetails_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_date',), 'verbose_name': 'All Registered customers', 'verbose_name_plural': 'All Registered customers'},
        ),
    ]
