# Generated by Django 3.2.9 on 2022-04-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(help_text='the device finger print is meant to be unique across all platform to identify the user login device for security purpose', max_length=455, null=True, verbose_name='Device Finger Print'),
        ),
    ]
