# Generated by Django 3.2.9 on 2022-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_user_device_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(default='null', help_text='the device finger print is meant to be unique across all platform to identify the user login device for security purpose', max_length=455, null=True, verbose_name='Device Finger Print'),
        ),
    ]
