# Generated by Django 3.2.9 on 2022-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_user_device_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(blank=True, help_text='this indicates which version of app the user is using , so to determine which when to pop up and update for the app.', max_length=255, null=True, verbose_name='Users App Version'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, help_text='the hold the users device type which is meant to updated when the user logs in.', max_length=300, null=True, verbose_name='Device Type'),
        ),
    ]
