# Generated by Django 3.2.9 on 2022-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_auto_20220403_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankdetails',
            name='integration_id',
            field=models.CharField(blank=True, help_text='this is the integration ID which is stored for reference purpose', max_length=255, null=True, verbose_name='Integration ID'),
        ),
        migrations.AddField(
            model_name='userbankdetails',
            name='recipient_code',
            field=models.CharField(blank=True, help_text='the recipient code is stored and used for withdrawal purpose. which is meant to be unique to per user and also its an auto generated code from the third party.', max_length=255, null=True, verbose_name='Recipient Code'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='account_name',
            field=models.CharField(blank=True, help_text='the customers bank account name.', max_length=70, null=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='account_number',
            field=models.CharField(blank=True, help_text='the customers bank account number for the bank', max_length=20, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_code',
            field=models.CharField(blank=True, help_text='The bankinig code which is required for the withdrawal.', max_length=25, null=True, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_id',
            field=models.CharField(blank=True, help_text='The bankinig ID which is required for the withdrawal.', max_length=3, null=True, verbose_name='Bank ID'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_name',
            field=models.CharField(blank=True, help_text='The bank name of the customer.', max_length=60, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='verified',
            field=models.BooleanField(blank=True, default=False, help_text='customers account verification status which determines whether the account number is verified or not .', null=True, verbose_name='Account Verified'),
        ),
    ]
