# Generated by Django 3.2.9 on 2022-05-15 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_businessprofile_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='workers',
            field=models.ManyToManyField(blank=True, help_text='this field holds the company workers profile account which will automatically be associated with the user profile account.', related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Worker Profile'),
        ),
    ]
