# Generated by Django 3.2.9 on 2022-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_alter_businessprofile_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the customer.', max_length=13, null=True, unique=True, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='null', help_text='the device finger print is meant to be unique across all platform to identify the user login device for security purpose', max_length=455, null=True, verbose_name='Device Finger Print'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, help_text='the device id is meant to be unique across all platform to identify for security reasons', max_length=455, null=True, verbose_name='Device ID'),
        ),
    ]
