# Generated by Django 3.2.9 on 2022-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_businessprofile_business_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='business registration number is used to identify the user business.', max_length=255, null=True, verbose_name='Business Registration Number'),
        ),
    ]
