# Generated by Django 3.2.9 on 2022-06-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20220601_1911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KisokFAQ',
            new_name='KioskFAQ',
        ),
    ]
