# Generated by Django 3.2.9 on 2022-06-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_categories', '0001_initial'),
        ('users', '0087_rename_kisokfaq_kioskfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_category',
            field=models.ForeignKey(blank=True, help_text='this shows the business category which the user will select from ', null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk_categories.category'),
        ),
    ]
