# Generated by Django 3.2.9 on 2022-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_categories', '0001_initial'),
        ('users', '0089_auto_20220604_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_category',
            field=models.ManyToManyField(blank=True, help_text='this shows the business category which the user will select from ', to='kiosk_categories.Category'),
        ),
    ]
