# Generated by Django 3.2.9 on 2022-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_alter_businessprofile_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, help_text='this shows the business type which the user will select from ', max_length=255, null=True, verbose_name='Business Type'),
        ),
    ]
