# Generated by Django 3.2.9 on 2022-06-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_businessprofile_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Retail Store', 'Retail Store'), ('Grocery Store', 'Grocery Store'), ('Convenient Store', 'Convenient Store'), ('Beauty and Fashion', 'Beauty and Fashion'), ('Electronics', 'Electronics'), ('Services', 'Services'), ('Others', 'Others')], help_text='this shows the business type which the user will select from ', max_length=255, null=True, verbose_name='Business Type'),
        ),
    ]
