# Generated by Django 3.2.9 on 2022-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_auto_20220612_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='accept_email_notifications',
            field=models.BooleanField(default=True, help_text='the active status bar indicates if the merchant business is on light mode or not ', null=True, verbose_name='Email Notification'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='accept_mobile_notifications',
            field=models.BooleanField(default=True, help_text='the active status bar indicates if the merchant business is on light mode or not ', null=True, verbose_name='Mobile Nofication'),
        ),
    ]
