# Generated by Django 3.2.9 on 2022-07-28 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_auto_20220618_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(help_text='The user for whom address belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='user',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='userwrongpinvalidate',
            name='user',
            field=models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
