# Generated by Django 3.2.9 on 2022-08-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_alter_user_country_of_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('merchant', 'Merchant')], default='personal', help_text='Account type', max_length=15, null=True, verbose_name='Account Type'),
        ),
    ]
