# Generated by Django 3.2.9 on 2022-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='active',
            field=models.BooleanField(default=False, help_text='the active status bar indicates if the merchant business is active or not', null=True, verbose_name='Active'),
        ),
    ]
