# Generated by Django 3.2.9 on 2022-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_cards', '0011_virtual_cards_details_card_design'),
        ('users', '0101_alter_businessprofile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='virtual_card',
            field=models.ManyToManyField(blank=True, help_text='This show the list of virtual card owned ny this user ', related_name='customer_virtual_cards', to='virtual_cards.Virtual_Cards_Details', verbose_name='User Virtual Cards'),
        ),
    ]
