# Generated by Django 3.2.9 on 2022-12-06 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_rename_virtual_card_user_virtual_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if customer has completed onboarding process.', verbose_name='Completed Onboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed onboarding process.', null=True, verbose_name='Onboarding Complete Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_user',
            field=models.ForeignKey(blank=True, help_text='this is the gov user account that provides the current user information for on boarding', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_on_boarding_user', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
