# Generated by Django 3.2.9 on 2022-12-06 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_auto_20221206_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='on_boarding_user',
            field=models.ForeignKey(blank=True, help_text='this is the gov user account that provides the current user information for on boarding', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_on_boarding_user', to=settings.AUTH_USER_MODEL, verbose_name='Gov Profile'),
        ),
    ]
