# Generated by Django 3.2.9 on 2022-12-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_alter_user_on_boarding_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_provence',
            field=models.CharField(blank=True, help_text='The users country provence', max_length=40, null=True, verbose_name='Country Provence'),
        ),
    ]
