# Generated by Django 3.2.9 on 2022-12-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_country_provience'),
        ('users', '0107_auto_20221207_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_province',
            field=models.ForeignKey(blank=True, help_text='The users country province', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country_provience', verbose_name='Country Province'),
        ),
    ]
