# Generated by Django 3.2.9 on 2023-01-12 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_alter_user_country_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_password',
            field=models.CharField(blank=True, help_text='this generated password is set to be the default password when an onboarding process is been taken place. its advisable to change the generated password', max_length=455, null=True, verbose_name='Generated Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='on_boarding_complete_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Timestamp when customer completed onboarding process.', null=True, verbose_name='Onboarding Complete Date'),
        ),
    ]
