# Generated by Django 3.2.9 on 2023-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_auto_20230112_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_details',
            field=models.BooleanField(default=False, help_text='email details section indicates if the email coontaining the user default details has been set or not . this operation is only taken place when an onboarding process is been completed', null=True, verbose_name='Email Details'),
        ),
    ]
