# Generated by Django 3.2.9 on 2023-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_user_email_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='simulate_account',
            field=models.BooleanField(default=False, help_text='this indicates that the current account is a simulated account which is not meant to be used for any live transaction', null=True, verbose_name='Simulated Account'),
        ),
    ]
