# Generated by Django 4.2.3 on 2023-08-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0111_user_simulate_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="government_organization",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="This indicates if the merchant is a registered government organization",
                null=True,
                verbose_name="Government Organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="government_organization_name",
            field=models.CharField(
                blank=True,
                choices=[("nasme_org1", "NASME_ORG1"), ("nasme_org2", "NASME_ORG2")],
                help_text="The government organization name holds the title name of the organisation that the merchant business is registered under",
                max_length=20,
                null=True,
                verbose_name="Government Organization Name",
            ),
        ),
    ]
