# Generated by Django 4.2.3 on 2023-08-07 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0112_user_government_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="government_organization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="government_organization_name",
        ),
    ]
