# Generated by Django 4.2.3 on 2023-08-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gov_panel", "0007_rename_government_organization_name_government_organizations_government_organization"),
        ("users", "0113_remove_user_government_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="government_organization",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="This indicates if the merchant is a registered government organization",
                null=True,
                verbose_name="Government Organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="government_organization_name",
            field=models.ForeignKey(
                blank=True,
                help_text="The government organization name holds the title name of the organisation that the merchant business is registered under",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gov_panel.government_organizations",
                verbose_name="Government Organization Name",
            ),
        ),
    ]
