# Generated by Django 4.2.3 on 2023-08-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0116_user_government_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="government_organization",
        ),
        migrations.AddField(
            model_name="user",
            name="government_registered",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="This indicates if the merchant is a registered government organization",
                null=True,
                verbose_name="Government Registered",
            ),
        ),
    ]
