# Generated by Django 3.2.9 on 2022-01-29 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPTs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('opt_code', models.CharField(help_text='opt code that will be sent to the user for validation and resting of transactional pin.', max_length=6, null=True, verbose_name='Opt Code')),
                ('duration', models.DateTimeField(default=django.utils.timezone.now, help_text='duration of which the opt will be expired from been used ny the user , which a new opt will be sent to the user to obtain a new opt token.', null=True, verbose_name='Opt Duration')),
                ('active', models.BooleanField(default=True, help_text='This status indicates whether otp is still active or not', null=True, verbose_name='OTP Active')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Opt Token',
                'verbose_name_plural': 'Opt Token',
                'ordering': ('-created_date',),
            },
        ),
    ]
