# Generated by Django 3.2.9 on 2022-01-29 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kroon_otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opts',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address of the requester', max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='opts',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
