# Generated by Django 3.2.9 on 2022-01-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_otp', '0003_alter_opts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opts',
            old_name='opt_code',
            new_name='otp_code',
        ),
    ]
