# Generated by Django 3.2.9 on 2022-01-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_otp', '0004_rename_opt_code_opts_otp_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opts',
            options={'ordering': ('-created_date',), 'verbose_name': 'Otp Token', 'verbose_name_plural': 'Otp Token'},
        ),
        migrations.RemoveField(
            model_name='opts',
            name='user',
        ),
    ]
