# Generated by Django 3.2.9 on 2022-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_otp', '0005_auto_20220130_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opts',
            name='otp_code',
            field=models.CharField(help_text='opt code that will be sent to the user for validation and resting of transactional pin.', max_length=255, null=True, verbose_name='Opt Code'),
        ),
    ]
