# Generated by Django 3.2.9 on 2022-04-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='toal amount taken for the cart.', max_digits=300, null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text=' amount paid taken by the customer.', max_digits=300, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('kroon_token', 'Kroon_Token'), ('card_payment', 'Card_Payment'), ('cash_payment', 'Cash_Payment')], default='card payment', help_text='The payment method used while paying for an order.', max_length=150, null=True, verbose_name='Payment Method'),
        ),
    ]
