# Generated by Django 3.2.9 on 2022-04-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0003_alter_merchant_product_merchant_local_currency'),
        ('kiosk_cart', '0002_auto_20220425_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='the list of ordered products for this particular checkout order', null=True, to='kiosk_stores.Merchant_Product', verbose_name='Ordered Products'),
        ),
    ]
