# Generated by Django 3.2.9 on 2022-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0004_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('kroon_token', 'Kroon Token'), ('card_payment', 'Card Payment'), ('cash_payment', 'Cash Payment')], default='card payment', help_text='The payment method used while paying for an order.', max_length=150, null=True, verbose_name='Payment Method'),
        ),
    ]
