# Generated by Django 3.2.9 on 2022-05-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_stores', '0005_auto_20220512_2322'),
        ('kiosk_cart', '0006_cartitem_product_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.IntegerField(blank=True, help_text='price for the current product.', null=True, verbose_name='Product Price '),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_total_price',
            field=models.IntegerField(blank=True, help_text='total price for the current product which is calculated by the quantity of the product with the product price.', null=True, verbose_name='Product Total Price '),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, help_text='foreign key and session to the product variation table.', to='kiosk_stores.ProductVariation'),
        ),
    ]
