# Generated by Django 3.2.9 on 2022-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0007_auto_20220513_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.CharField(blank=True, help_text='this store the workers name that checkout the products for the particular store', max_length=250, null=True, verbose_name='Worker'),
        ),
    ]
