# Generated by Django 3.2.9 on 2022-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0012_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, help_text='product quantity for the current product been order by the customer.', null=True, verbose_name='Product Quantity'),
        ),
    ]
