# Generated by Django 3.2.9 on 2022-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0013_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='price for the current product.', max_digits=300, null=True, verbose_name='Product Price '),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='total price for the current product which is calculated by the quantity of the product with the product price.', max_digits=300, null=True, verbose_name='Product Total Price '),
        ),
    ]
