# Generated by Django 3.2.9 on 2022-06-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0014_auto_20220530_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='weight_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='the stores the product quantity via weight', max_digits=300, null=True, verbose_name='Weight Quantity'),
        ),
    ]
