# Generated by Django 3.2.9 on 2022-06-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0016_orderproduct_weight_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cash_collected',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='toal amount taken for the cart.', max_digits=300, null=True, verbose_name='Total Cash Amount Collect'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='customers_change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='toal amount taken for the cart.', max_digits=300, null=True, verbose_name='Total Customers Change'),
        ),
    ]
