# Generated by Django 3.2.9 on 2022-06-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0019_auto_20220608_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cash_collected',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='customers_change',
        ),
    ]
