# Generated by Django 3.2.9 on 2022-06-09 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk_cart', '0020_auto_20220608_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='toal amount taken for this manual sale', max_digits=300, null=True, verbose_name='Total Amount Paid')),
                ('order_number', models.CharField(help_text='Order generated number to identify the current customer order', max_length=150, null=True, verbose_name='Order Number')),
                ('worker', models.CharField(blank=True, help_text='this store the workers name that checkout the products for the particular store', max_length=250, null=True, verbose_name='Worker')),
                ('is_ordered', models.BooleanField(blank=True, default=False, help_text='the current state of the order , which identifies if the order is been processed successfully or not.', null=True, verbose_name='Order Operation')),
                ('user', models.ForeignKey(help_text='The user the manual sale belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Manual Sale',
                'verbose_name_plural': 'Manual Sale',
                'ordering': ('-created_date',),
            },
        ),
    ]
