# Generated by Django 3.2.9 on 2022-06-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0021_manual_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manual_Sale',
        ),
    ]
