# Generated by Django 3.2.9 on 2023-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0024_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund',
            field=models.BooleanField(blank=True, default=False, help_text='this indicates if the actual order is been refunded or not.', null=True, verbose_name='Order Refund'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='refund',
            field=models.BooleanField(blank=True, default=False, help_text='this indicates if the actual product is been refunded or not.', null=True, verbose_name='Product Refund'),
        ),
    ]
