# Generated by Django 3.2.9 on 2023-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_cart', '0025_auto_20230402_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='refund_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='price for the current Refund product.', max_digits=300, null=True, verbose_name='Refund Product Price '),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='refund_quantity',
            field=models.IntegerField(blank=True, default=0, help_text=' Refund product quantity for the current product been order by the customer.', null=True, verbose_name='Refund Product Quantity'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='refund_weight_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='the stores the Refund product quantity via weight', max_digits=300, null=True, verbose_name=' Refund Weight Quantity'),
        ),
    ]
