# Generated by Django 3.2.9 on 2022-06-02 15:29

from django.db import migrations, models
import django.utils.timezone
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('plan_name', models.CharField(blank=True, help_text='the will be the subscription plan, provided by the admin ', max_length=50, null=True, verbose_name='Plan Name')),
                ('plan_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='transactional amount taken by the customer.', max_digits=300, null=True, verbose_name='Plan Fee')),
                ('plan_duration', models.IntegerField(blank=True, help_text='this holds the plan duration in days', null=True, verbose_name='Plan Duration')),
                ('plan_default_currency', models.CharField(blank=True, help_text='the plan default currency is used to identify which currency should the plan payment be made with.', max_length=20, null=True, verbose_name='Default Plan Currency')),
                ('plan_content', tinymce.models.HTMLField()),
                ('active', models.BooleanField(default=True, help_text='this indicates whether the promotional code is active or not.', null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Subcription Plans',
                'verbose_name_plural': 'Subscription Plan',
                'ordering': ('-created_date',),
            },
        ),
    ]
