# Generated by Django 3.2.9 on 2022-06-03 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant_Subcribers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the subscription was created.', max_length=20, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='Timestamp when the subscription was expire.', max_length=20, verbose_name='End Date')),
                ('active', models.BooleanField(default=True, help_text='this indicates whether the promotional code is active or not.', null=True, verbose_name='Status')),
                ('plan', models.ForeignKey(blank=True, help_text='the will be the subscription plan, provided by the admin ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='subscriptions.subscription_plan')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_subcribers', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Merchant Subscribers',
                'verbose_name_plural': 'Merchant Subscribers',
                'ordering': ('-created_date',),
            },
        ),
    ]
