# Generated by Django 3.2.9 on 2022-06-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_merchant_subcribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='default_plan',
            field=models.BooleanField(blank=True, default=False, help_text='this indicates that this current plan is meant to be the defualt plan for merchant users.', null=True, verbose_name='Defualt Plan'),
        ),
    ]
