# Generated by Django 3.2.9 on 2022-06-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_plan_default_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_subcribers',
            name='active',
            field=models.BooleanField(default=False, help_text='this indicates whether the promotional code is active or not.', null=True, verbose_name='Status'),
        ),
    ]
