# Generated by Django 3.2.9 on 2022-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_merchant_subcribers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='yearly_plan',
            field=models.BooleanField(blank=True, default=False, help_text='this indicates that this current plan is meant to be a yearly plan or not ', null=True, verbose_name='Year Plan'),
        ),
        migrations.AddField(
            model_name='subscription_plan',
            name='yearly_plan_duration',
            field=models.IntegerField(blank=True, help_text='this holds the plan duration in days', null=True, verbose_name='Yearly Plan Duration'),
        ),
        migrations.AddField(
            model_name='subscription_plan',
            name='yearly_plan_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='yearly plan amount to be charged to the subscripers in a year.', max_digits=300, null=True, verbose_name='Yearly Plan Fee'),
        ),
        migrations.AlterField(
            model_name='subscription_plan',
            name='plan_default_currency',
            field=models.CharField(blank=True, default='USD', help_text='the plan default currency is used to identify which currency should the plan payment be made with.', max_length=20, null=True, verbose_name='Default Plan Currency'),
        ),
    ]
