# Generated by Django 3.2.9 on 2022-07-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_merchant_subcribers_yearly_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='monthly_plan_id',
            field=models.CharField(blank=True, help_text='this hold the plan recurring id , which is been requested for subscription recurring payment', max_length=200, null=True, verbose_name='Monthly Plan ID'),
        ),
        migrations.AddField(
            model_name='subscription_plan',
            name='yearly_plan_id',
            field=models.CharField(blank=True, help_text='this hold the plan recurring id , which is been requested for subscription recurring payment', max_length=200, null=True, verbose_name='Yearly Plan ID'),
        ),
    ]
