# Generated by Django 3.2.9 on 2022-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20220716_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_subcribers',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='subscription id holds the id given to deactivating and activating a recurring payment', max_length=255, null=True, verbose_name='Subscription ID'),
        ),
    ]
