# Generated by Django 3.2.9 on 2022-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_merchant_subcribers_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_subcribers',
            name='recurring_payment',
            field=models.BooleanField(blank=True, default=True, help_text='this indicates if the subscription payment is recurring or not, which can also be deactivated by the user.', null=True, verbose_name='Recurring Payment'),
        ),
    ]
