# Generated by Django 3.2.9 on 2022-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_merchant_subcribers_recurring_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_subcribers',
            name='sub_plan_id',
            field=models.CharField(blank=True, help_text='subscription plan id holds the id given to deactivating and activating a recurring payment', max_length=255, null=True, verbose_name='Subscription Plan ID'),
        ),
    ]
