# Generated by Django 4.1.9 on 2023-05-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_alter_merchant_subcribers_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription_plan",
            name="gov_yearly_plan_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="government yearly plan amount to be charged to the subscripers in a year.",
                max_digits=300,
                null=True,
                verbose_name="Gov Yearly Plan Fee",
            ),
        ),
    ]
