# Generated by Django 4.1.9 on 2023-06-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0014_remove_subscription_plan_gov_yearly_plan_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant_subcribers",
            name="sub_plan_id",
            field=models.CharField(
                blank=True,
                help_text="this plan id holds the id given to identify the subscription plan of the user which cna be the yearly plan id or the monthly plan id",
                max_length=255,
                null=True,
                verbose_name="Yearly Plan ID",
            ),
        ),
    ]
