# Generated by Django 4.2.3 on 2023-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0016_alter_merchant_subcribers_sub_plan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription_plan",
            name="slug_plan_name",
            field=models.CharField(
                blank=True,
                help_text="the will be the subscription plan, provided by the admin ",
                max_length=50,
                null=True,
                verbose_name="Slug Plan Name",
            ),
        ),
    ]
