# Generated by Django 3.2.9 on 2022-01-26 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('full_name', models.CharField(help_text='The legal full name of the user which the account belong to.', max_length=255, null=True, verbose_name='Full Name')),
                ('currency', models.CharField(help_text='this is the defualt currency for the user mobile money account.', max_length=255, null=True, verbose_name='Currency')),
                ('email', models.EmailField(help_text='email address for the current user', max_length=254, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text='the user phone number which is registered for the mobile money service.', max_length=25, null=True, verbose_name='UserPhone Number')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='the user IP address for his or her device.', null=True, verbose_name='User IP Address')),
                ('device_fingerprint', models.CharField(help_text='the users device fingerprint , which can be unique to a particular user.', max_length=255, null=True, verbose_name='Device Fingerprint')),
                ('network', models.ForeignKey(blank=True, help_text='mobile money network providers which is only accepted for countries like Ghana, Zambia.', null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_money.networkprovider')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Mobile Money Users Account',
                'verbose_name_plural': 'Mobile Money Users Account',
                'ordering': ('-created_date',),
            },
        ),
    ]
