# Generated by Django 3.2.9 on 2022-01-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_money', '0002_mobilemoneyaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneyaccount',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='mobilemoneyaccount',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='mobilemoneyaccount',
            name='full_name',
        ),
    ]
