# Generated by Django 3.2.9 on 2022-01-31 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_money', '0003_auto_20220131_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('amount', models.FloatField(help_text='The amount funded by the user using mobile money', null=True, verbose_name='Amount')),
                ('currency', models.CharField(help_text='Currency used for mobile money topup by the user', max_length=255, null=True, verbose_name='Currency')),
                ('email', models.EmailField(help_text='Email used for mobile money topup by the user', max_length=255, null=True, verbose_name='Email')),
                ('transactional_ref', models.CharField(help_text='Transactional refrence for the current payment initiated by the user', max_length=255, null=True, verbose_name='Transactional Reference')),
                ('phone_number', models.CharField(help_text='the current phone number used to initiate the mobile money transaction', max_length=255, null=True, verbose_name='Phone Number')),
                ('network', models.CharField(blank=True, help_text='mobile money network provider used', max_length=255, null=True, verbose_name='Network Provider')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Mobile Money TopUp',
                'verbose_name_plural': 'Mobile Money TopUp',
                'ordering': ('-created_date',),
            },
        ),
    ]
