# Generated by Django 3.2.9 on 2022-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_money', '0006_alter_mobilemoneyaccount_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneyaccount',
            name='withdrawal_code',
            field=models.CharField(blank=True, default='MPS', help_text='The withdrawal code is used when the user requested for a mobile money withdrawal, for countries like Uganda, Zambia and Rwanda , while making use of the network providers during mobile money withdrawal for Ghana.', max_length=255, null=True, verbose_name='Account Code'),
        ),
    ]
