# Generated by Django 3.2.9 on 2022-03-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='accept_kroon',
            field=models.BooleanField(default=True, help_text='Allow users from country to register.', verbose_name='Accept Kroon Users'),
        ),
    ]
