# Generated by Django 3.2.9 on 2022-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_accept_kroon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='accept_kroon',
            field=models.BooleanField(default=False, help_text='Allow users from country to register.', verbose_name='Accept Kroon Users'),
        ),
    ]
