# Generated by Django 3.2.9 on 2022-12-12 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_Provience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provience', models.CharField(blank=True, help_text=' this is the name of the province', max_length=40, null=True)),
                ('active', models.BooleanField(default=False, help_text='Indicate if province is active or not', verbose_name='Active')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created', verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified.', verbose_name='Modified Date')),
                ('country', models.ForeignKey(help_text=' this holds the record for the country which the province belongs to ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country')),
            ],
            options={
                'verbose_name': 'Country Province',
                'verbose_name_plural': 'Country Province',
                'db_table': 'countries_province',
            },
        ),
    ]
