# Generated by Django 3.2.9 on 2022-12-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_alter_user_country_province'),
        ('locations', '0005_country_provience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country_Provience',
            new_name='Country_Province',
        ),
        migrations.RenameField(
            model_name='country_province',
            old_name='provience',
            new_name='province',
        ),
    ]
