# Generated by Django 4.2.5 on 2023-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_auto_20221212_1021"),
        ("admin_reports", "0004_remove_adminpushnotifications_device_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminpushnotifications",
            name="news_feed_country",
            field=models.ManyToManyField(
                help_text="The country that is only valid to view this news feed ",
                null=True,
                to="locations.country",
                verbose_name="News Feed Country",
            ),
        ),
        migrations.AlterField(
            model_name="adminpushnotifications",
            name="platform",
            field=models.CharField(
                choices=[("all_the_above", "all_the_above"), ("kroon", "kroon"), ("kroon kiosk", "kroon_kiosk")],
                default="all_the_above",
                help_text="The platform that is only valid to view this news feed specified for the paltform only , which can also be identified as the 'all the above' which shows all the contents for kroon and kroon kiosk to the users",
                max_length=30,
                null=True,
            ),
        ),
    ]
