# Generated by Django 4.2.5 on 2023-10-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_reports", "0007_alter_adminpushnotifications_news_feed_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminpushnotifications",
            name="title",
            field=models.CharField(
                help_text="The notification title that will be displayed to the user mobile device.",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
