# Generated by Django 4.2.5 on 2023-10-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_reports", "0008_alter_adminpushnotifications_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminpushnotifications",
            name="platform",
            field=models.CharField(
                choices=[("KROON", "KROON"), ("KIOSK", "KIOSK"), ("GENERAL", "GENERAL")],
                default="GENERAL",
                help_text="This holds the platform that is only valid to recieve the push notification, which can also be identified as the 'all the above' which shows the contents for devices and platforms that is registered under kroon network.",
                max_length=30,
                null=True,
            ),
        ),
    ]
