# Generated by Django 4.2.5 on 2023-10-16 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_auto_20221212_1021"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_reports", "0009_alter_adminpushnotifications_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNewsFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the record was created. The date and time \n            are displayed in the Timezone from where request is made. \n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was modified. The date and \n            time are displayed in the Timezone from where request \n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The notification title that will be displayed to the user mobile device.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "body_message",
                    models.TextField(
                        help_text="this holds the content of the push notification",
                        null=True,
                        verbose_name="Body Message",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="news feed image that will be displayed to the user",
                        null=True,
                        upload_to="news_feed/",
                        verbose_name="News Feed Image",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("KROON", "KROON"), ("KIOSK", "KIOSK"), ("GENERAL", "GENERAL")],
                        default="GENERAL",
                        help_text="This holds the platform that is only valid to recieve the push notification, which can also be identified as the 'all the above' which shows the contents for devices and platforms that is registered under kroon network.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        help_text="this storess the device type in which the push notifications is been sent to",
                        max_length=25,
                        null=True,
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        help_text="the notification type is the type of notification that is been sent by the admin",
                        max_length=25,
                        null=True,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="notification status which determines whether the feed should be shown or not",
                        null=True,
                        verbose_name="Notification Status",
                    ),
                ),
                (
                    "news_feed_country",
                    models.ManyToManyField(
                        help_text="The country that is only valid to view this ",
                        to="locations.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        help_text="This holds the publisher name ",
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Notification",
                "verbose_name_plural": "Push Notification",
                "ordering": ("-created_date",),
            },
        ),
        migrations.DeleteModel(
            name="AdminPushNotifications",
        ),
    ]
