# Generated by Django 3.2.9 on 2022-06-27 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient_Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('integration_id', models.CharField(blank=True, help_text='this is the integration ID which is stored for reference purpose', max_length=255, null=True, verbose_name='Integration ID')),
                ('recipient_code', models.CharField(blank=True, help_text='the recipient code is stored and used for withdrawal purpose. which is meant to be unique to per user and also its an auto generated code from the third party.', max_length=255, null=True, verbose_name='Recipient Code')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_user', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Recipient Record',
                'verbose_name_plural': 'Recipient Record',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Kroon_Withdrawal_Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('full_name', models.CharField(blank=True, help_text='full name of the current user used for transfer.', max_length=255, null=True, verbose_name='Full Name')),
                ('account_number', models.CharField(blank=True, help_text='Account number is been used to identify the users account, which can be the bank issued number to the user for local bank withdrawal and when it comes to mobile money withdrawl the account number field will be replace by the mobile number.', max_length=255, null=True, verbose_name='Account Number')),
                ('beneficiary_name', models.CharField(blank=True, help_text='the beneficary name of the user that want to perform the withdrawal note this will only be inputted if the user has stored his or her account details for withdrawal', max_length=255, null=True, verbose_name='Beneficiary Name')),
                ('recipient_code', models.CharField(blank=True, help_text='the recipent ref noumber is provided by the third party providers , which will be used to initiate the local bank or mobile money transfer.', max_length=150, null=True, verbose_name='Recipient code Record')),
                ('recipient_codetwo', models.CharField(blank=True, help_text='the recipent ref noumber is provided by the third party providers , which will be used to initiate the local bank or mobile money transfer.', max_length=150, null=True, verbose_name='Recipient code Record')),
                ('transaction_id', models.CharField(blank=True, help_text='transactional id is the unique identifier of the transaction which will be provided by the payment gateway for easy verification and comfirmation of a transaction.', max_length=255, null=True, verbose_name='transaction ID')),
                ('bank_name', models.CharField(blank=True, help_text='Bank name used for mobile money accounts and local bank withdrawal bank name', max_length=255, null=True, verbose_name='Moble Money - Bank Name')),
                ('bank_code', models.CharField(blank=True, help_text='Bank name used for mobile money accounts', max_length=255, null=True, verbose_name='Bank Name Code')),
                ('amount', models.DecimalField(decimal_places=2, help_text='amount of withdrawal which the user initiated to be withdrawed to his or her account.', max_digits=300, max_length=255, null=True, verbose_name='Amount')),
                ('amount_in_kroon', models.DecimalField(decimal_places=2, help_text='amount in kroon of withdrawal which the user initiated to be withdrawed to his or her account.', max_digits=300, max_length=255, null=True, verbose_name='Amount In Kroon')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, help_text='the initial fees for that transaction which the user initiated to be withdrawed to his or her account.', max_digits=300, max_length=255, null=True, verbose_name='Fees Amount')),
                ('currency', models.CharField(help_text='currency of withdrawal request by the user defualt currency type.', max_length=255, null=True, verbose_name='Currency')),
                ('debit_currency', models.CharField(blank=True, help_text='currency of withdrawal request by the user defualt currency type.', max_length=255, null=True, verbose_name='Debit Currency')),
                ('reference', models.CharField(help_text='this holds the reference to the current transaction request.', max_length=255, null=True, verbose_name='Reference')),
                ('paystack_reference', models.CharField(blank=True, help_text='this holds the reference issued from paystack to the current transaction request by the customer.', max_length=255, null=True, verbose_name='Paystack Reference')),
                ('billing_full_name', models.CharField(blank=True, help_text='Billing full name of the user.', max_length=255, null=True, verbose_name='Billing Full Name')),
                ('billing_email', models.EmailField(blank=True, help_text='This is the email address of the transfer recipient', max_length=255, null=True, verbose_name='Billing Email')),
                ('billing_mobile_number', models.CharField(blank=True, help_text="This is the mobile number of the recipient. If the recipient's email address is passed, this becomes an optional parameter.", max_length=255, null=True, verbose_name='Billing Phone Number')),
                ('billing_recipient_address', models.TextField(blank=True, help_text='This is the address of the transfer recipient.', null=True, verbose_name='Billing Address')),
                ('action', models.CharField(help_text='this indicate which transfer was taken place ether with card or mobile', max_length=255, null=True, verbose_name='Action')),
                ('is_approved', models.BooleanField(default=False, help_text='indicates if the withdrawal has been approved or not .', null=True, verbose_name='Withdrawal Approved')),
                ('status', models.CharField(help_text='initiate a withdraw which indicates if it is true or false.', max_length=50, null=True, verbose_name='Status')),
                ('withdrawal_type', models.CharField(blank=True, help_text='this indicates the withdrawal type the user initiated to use.', max_length=300, null=True, verbose_name='Withdrawal Type')),
                ('date_requested', models.DateField(blank=True, help_text='this indicates the actual date the user initiated the withdrawal.', null=True, verbose_name='Date Requested')),
                ('estimated_delivery', models.DateField(blank=True, help_text='this indicates the actual date the user  withdrawal was suubmitted.', null=True, verbose_name='Estimated Delivery Date')),
                ('narration', models.CharField(blank=True, help_text='transactional narration which is used to pass the message to the third party, reasons for the withdrawal.', max_length=255, null=True, verbose_name='Narration')),
                ('settled', models.BooleanField(blank=True, default=False, help_text='this helps in indicating if the transaction is been settled or not.', null=True, verbose_name='Settled')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'All Withdrawals',
                'verbose_name_plural': 'All Withdrawals',
                'ordering': ('-created_date',),
            },
        ),
    ]
