# Generated by Django 3.2.9 on 2022-06-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroon_withdrawal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kroon_withdrawal_record',
            name='recipient_codetwo',
        ),
    ]
