# Generated by Django 3.2.9 on 2022-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_accept_kroon'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='news_feed_country',
            field=models.ManyToManyField(help_text='The country that is only valid to view this news feed ', to='locations.Country', verbose_name='News Feed Country'),
        ),
    ]
