# Generated by Django 3.2.9 on 2022-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_newsfeed_news_feed_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='platform',
            field=models.CharField(blank=True, choices=[('all the above', 'all_the_above'), ('kroon', 'Kroon'), ('kroon kiosk', 'kroon_kiosk')], default='all the above', help_text="The platform that is only valid to view this news feed specified for the paltform only , which can also be identified as the 'all the above' which shows all the contents for kroon and kroon kiosk to the users", max_length=255, null=True),
        ),
    ]
