# Generated by Django 3.2.9 on 2022-08-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_newsfeed_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='platform',
            field=models.CharField(blank=True, choices=[('all_the_above', 'all_the_above'), ('kroon', 'kroon'), ('kroon kiosk', 'kroon_kiosk')], default='all_the_above', help_text="The platform that is only valid to view this news feed specified for the paltform only , which can also be identified as the 'all the above' which shows all the contents for kroon and kroon kiosk to the users", max_length=255, null=True),
        ),
    ]
