# Generated by Django 3.2.9 on 2023-02-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_newsfeed_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Approved date is when the record is been approved by the gov super admin.', max_length=20, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='publisher',
            field=models.CharField(blank=True, help_text='This holds the publisher name ', max_length=255, null=True, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='publishing_time',
            field=models.DateTimeField(blank=True, help_text='Publishing Date will be calculated automatically adding 3 mins to the current time , which will automatically be published when it up to the published time.', max_length=20, null=True, verbose_name='Publishing Date'),
        ),
    ]
