# Generated by Django 3.2.9 on 2023-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20230203_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='gov_post',
            field=models.BooleanField(blank=True, default=False, help_text='this is to indicate that the current post or news feed is a government news feed', null=True, verbose_name='Gov Post Status'),
        ),
    ]
